### ISSUE TITLE
Homework for week 1 is published.

### ISSUE THREAD

**Issue by alxest** [snu-sf-class/pp201602#1]
I published homework for week 1 [here](https://github.com/snu-sf-class/pp201602/tree/master/hw/01).
All you need to see is [this](https://github.com/snu-sf-class/pp201602/blob/master/hw/01/src/main/scala/submission/Main.scala).

**Comment by alxest** [comment]
I will notice submission web site soon...

**Comment by alxest** [comment]
For each homework, you are allowed to submit *SINGLE* file, named "Main.scala".
So do not change other parts, or your code will behave in unexpected way during the test.

**Comment by alxest** [comment]
Wart's rule ListOps is removed: https://github.com/snu-sf-class/pp201602/issues/3#issuecomment-245176463

**Comment by alxest** [comment]
Problem spec for "bbalance" is updated.

**Comment by alxest** [comment]
한글 수업이라고 하셔서 한글로 공지합니다.
프로젝트 디렉토리가 변경되었습니다.
이제 프로젝트 디렉토리는 여기: https://github.com/snu-sf-class/pp201602/tree/master/hw/01
메인 스칼라 파일은 여기: https://github.com/snu-sf-class/pp201602/blob/master/hw/01/src/main/scala/submission/Main.scala
에 있습니다. 불편을 드려 죄송합니다.

**Comment by alxest** [comment]
중요 공지 
===========================================
1. 숙제1 문제가 변경될 예정입니다. 문제 2/3번에서 List가 나왔는데, List를 아직 배우지 않았기 때문에, 배운 후로 연기할 예정입니다. 문제는 곧 업데이트될 예정입니다.
2. 숙제1 기한은 다음주 일요일로 변경되었습니다. 이후 숙제도 1주씩 밀릴 예정입니다.

**Comment by 13oris** [comment]
죄송한데 숙제가 정확히 뭔지 다시 한번만 알려주시겠어요?

**Comment by pocca2048** [comment]
@alxest 중요 공지는 잘보이도록 메인 화면에 띄워주시는게 낫지 않을까요? 
기존 이슈에 덧글로 붙이면 깃헙에 익숙하지 않은 분들은 못보고 넘어갈 수도 있을 것 같네요

**Comment by jeuxdeau** [comment]
@13oris hw/01/src/main/scala/submission/Main.scala 파일의 주석 부분에 있습니다. 깃허브에 익숙지 않은 분들을 위해 과제 제출을 위한 기본적인 안내가 있으면 좋겠습니다.

**Comment by GiWoongLee** [comment]
안녕하세요, 조교님. PP 수업을 듣는 이기웅입니다.

숙제1 변경에 대한 질문이 있어 글 남깁니다.

1. 제출일자 - 12일에 글을 올려주신 거 같은데, 12일 기준으로 다음주 일요일이면 제출일자가 25일이 되는건가요?
2. 문제 - 2/3번 문제가 List가 있는 걸로 보니, 아직 업데이트 되지 않았다고 보면 되나요? 문제는 언제 업데이트 되나요?

감사합니다.

**Comment by alxest** [comment]
[숙제 01](https://github.com/snu-sf-class/pp201602/tree/master/hw/01)이 재업로드되었습니다.
[Main.scala](https://github.com/snu-sf-class/pp201602/blob/master/hw/01/src/main/scala/submission/Main.scala) 파일에 필요한 내용들을 적어두었습니다.
데드라인도 그에 따라 9월28일 23:59분으로 연기하였습니다. 메인 페이지에 공지하였습니다.

**Comment by alxest** [comment]
@13oris @pocca2048 @GiWoongLee 
윗 댓글 확인 부탁드립니다.
@jeuxdeau 숙제 제출 사이트는 준비되는대로 공지하겠습니다. 준비가 늦어져서 죄송합니다. 이번 수요일 전까지는 준비해보겠습니다.

**Comment by Choi-Jaehyeok** [comment]
안녕하세요 조교님. 몇 가지 여쭤볼 게 있습니다.
1. 숙제 제출 사이트가 공지된 것이 맞나요? 제가 놓치거나 깜빡한 게 있는 거 같은 기분이 들어서 여쭤봅니다...
2. 공지된 것이 맞다면, 사이트를 깃허브 issues에 공지해 주실 수 있으신가요?

**Comment by alxest** [comment]
fibC 관련하여: fibB와 입력 범위는 같지만, 실행 시 stack 크기를 제한하여 tail recursion 을 구현했는지 확인할 계획이었습니다. 이런 채점 방식이 혼란스럽다는 이야기가 있어서, 그냥 fibC의 경우에도 같은 stack 크기로 하고, 입력 범위를 10^5 까지로 하겠습니다. 제대로 구현되어있다면 통과하던게 통과를 못하는 일은 없을 것입니다.
감사합니다.

**Comment by alxest** [comment]
문자/메일로 공지한 바와 같이 숙제01 듀를 10월 10일로 연기합니다. 그리고 과제 제출 서버는 준비가 완료되는대로 문자/메일로 다시 공지드리도록 하겠습니다.
불편을 끼쳐드려 죄송합니다.
