### ISSUE TITLE
과제 제출 방식을 설명해주시면 좋겠습니다.

### ISSUE THREAD

**Issue by kj4569** [snu-sf-class/pp201602#10]
이 사이트를 처음 이용해보는터라 과제를 어떻게 제출해야하는지 잘 모르겠습니다.
어디로 무엇을 제출하면 되는지 알려주시면 감사하겠습니다.

**Comment by alxest** [comment]
과제 제출은 별도의 사이트에서 이루어질 예정입니다.
아직 공지된 바가 없으며 이번 주 수요일 전까지 공지해보겠습니다.
