### ISSUE TITLE
과제 6번 관련 질문입니다.

### ISSUE THREAD

**Issue by frmh0313** [snu-sf-class/pp201602#100]
주석에 "You may need to create your own class in this exercise."라고 되어있는데, 이 부분은 BiIterableTree[A]에 대해서 이야기하는 건가요? 아니면 스펙으로 주어진 것 외에 다른 클래스를 만드는 경우까지 고려가 된 것인가요?

**Comment by alxest** [comment]
스펙으로 주어진 것 외에 다른 클래스를 만드는 경우를 의미합니다.

**Comment by frmh0313** [comment]
네 감사합니다.
