### ISSUE TITLE
append 함수에 대해서 질문이 있습니다.

### ISSUE THREAD

**Issue by sangjaekang** [snu-sf-class/pp201602#101]
리스트 중 mycons를 아래와 같이 정의를 하였을 때,
	case class MyCons[A](val hd : A, val tl : MyList[A]) extends MyList[A] {
		def getValue = Some(hd)
		def getNext  = tl
		def append(lst: MyList[A]) = MyCons(hd,tl.append(lst))
	}
(( 수업 중에 다룬 코드라, 핵심 부분만 올리겠습니다))
append함수가 어떤 동작 방식으로, tree를 list 화 시키는지 이해가 잘 되지 않습니다.

트리의 노드가 이런식으로 정의되면서, left먼저 풀어지고 그 다음 right가 되는데,
case class Node[A](value : A, left: MyTree[A], right: MyTree[A]) extends MyTree[A]{
		def iter = MyCons(value, left.iter.append(right.iter))
}
append의 동작 원리에 대해서 알려주실 수 있나요?

**Comment by Ailrun** [comment]
append는 단순히 두 개의 리스트를 합치는 함수일 뿐입니다.
`MyCons(1, MyCons(2, MyNil())).append(MyCons(3,MyCons(4,MyNil())))`
을 부르면 결과는
`MyCons(1, MyCons(2, MyCons(3, MyCons(4, MyNil()))))` 이 됩니다.

Tree의 경우에 append를 사용하는 것은
> left subtree를 list화 시킨 후,
> 거기에 right subtree를 리스트화 시킨 것을 합친 리스트를 만들고, 
> 그 앞에 value를 놓는다.

일 뿐입니다.
