### ISSUE TITLE
숙제 4_new 채점에 대해서 질문이 있습니다

### ISSUE THREAD

**Issue by greemd** [snu-sf-class/pp201602#106]
오늘 숙제 4_new 채점 결과를 확인해보니 400/500이 나왔는데, 로그를 확인해보니 500점을 얻은것으로 되어있습니다. 로그의 점수와 실제 점수가 다를 수 있나요?

Submission번호는 1090번입니다.

**Comment by jeuxdeau** [comment]
딜레이 감점 아닌가요?

**Comment by greemd** [comment]
아, 그러네요. 답변 감사합니다
