### ISSUE TITLE
중간 고사 관련 질문

### ISSUE THREAD

**Issue by leegangtoe** [snu-sf-class/pp201602#116]
혹시 중간고사 시험문제와 풀이를 공개해 수 있으신가요??
시험결과가 언제 나오는지 궁금합니다.
또 과제 7은 언제쯤 나오나요.

**Comment by alxest** [comment]
문제와 풀이는 오늘 (11월 28일) 중으로 공개하겠습니다.
시험 결과는 시험 끝나고 하루 후에 기계적으로 채점은 되었습니다만, 몇가지 작업이 끝난 후 공개할 예정입니다. 이번주 내로는 공개될 듯 합니다.

**Comment by alxest** [comment]
늦어져서 죄송합니다. 내일 중으로는 공개하겠습니다. 물리적으로 시간이 없네요..

**Comment by alxest** [comment]
https://github.com/snu-sf-class/pp201602/issues/130
