### ISSUE TITLE
과제 7 trait ComplexNumberSpec에서 val 수정

### ISSUE THREAD

**Issue by leegangtoe** [snu-sf-class/pp201602#118]
ComplecNumberImpl class 에서 real, imaginary, magnitude, angle field를 수정하려고 하는데 잘 되지 않습니다. if 문안에 override def를 사용하면 compile이 되지 않는데 어떤식으로 수정할 수있나요?
또 위 필드들을 trait ComplexNumberSpec에서 왜 def가 아니라 val을 써서 정의했는지 궁금합니다.
def로 필드를 정의해 놓는게 더 합리적인 구현 같아서요.

**Comment by alxest** [comment]
- 수정이라는게 무슨 의미인지 모르겠습니다. 정의되어있는 것이 없는데 무엇을 수정한다는 것인가요? 정의를 하면 됩니다.
- if문 안에 override def를 넣는게 가능하다면 var를 쓰는거나 다름 없습니다. 일단 불가능하고 (java에서도 불가능할 듯) 가능하더라도 이 과목에서는 허용되지 않습니다. 힌트를 드리자면 override 도 필요 없습니다...
- val로 정의한 것은 불릴 때마다 여러번 계산하지 않기 때문입니다. def는 불릴 때마다 계산합니다.
