### ISSUE TITLE
과제 7에서의 trait ComplexNumberImpl 부분

### ISSUE THREAD

**Issue by pigbug419** [snu-sf-class/pp201602#121]
뼈대코드에서는 

`class ComplexNumberImpl (isRectangular: Boolean, arg1: Double, arg2: Double) `
`extends ComplexNumberSpec`
`      with ComplexNumberAdd`
`      with ComplexNumberMult`
`      with ComplexNumberEval {`
`  }`

이런 식으로 ComplexNumberImpl 안에는 ???가 없는데
이 부분은 채워넣지 않고 위에 ComplexNumberAdd, ComplexNumberMult, ComplexNumberEval만 구현을 해서
이 trait만을 상속받은 것으로 ComplexNumberImpl이 자동으로 구현될 수 있도록 코드를 짜야 하는 건가요?
아니면 ComplexNumberImpl 안에도 코드를 넣을 수 있는 건가요?

**Comment by alxest** [comment]
넣으실 수 있고, 넣지 않으면 구현이 안될 것입니다. (real, imaginary 등 정의)

**Comment by alxest** [comment]
주석 참조:
```
   You may get compile error for now, for missing signatures.
   Implement each missing fields so that it compiles.```
