### ISSUE TITLE
과제 7) eval 함수 관련 질문합니다.

### ISSUE THREAD

**Issue by HyjK** [snu-sf-class/pp201602#122]
안녕하세요?

trait ComplexNumberEval 아래 
def eval(coeffs: List[ComplexNumberEval]): ComplexNumberSpec 

함수에서 인자가 Nil 로 주어지는 경우가 있나요? 
그 경우 result type의 인자를 올바르게 반환하는 방법이 제가 생각해낼 수 있는 것은 this 밖에 없는데, evaluate 할 값이 없는 경우 원래 숫자를 그대로 반환하는 것이 자연스러운 구현인지 잘 모르겠습니다.
테스트 케이스로 들어가는 경우가 있는지, 그 경우 어떻게 하면 좋을지 기준이 있었으면 좋겠습니다.

감사합니다. :)

**Comment by alxest** [comment]
혹시 add, mult 구현 시에는 어떻게 ComplexNumberSpec을 리턴하셨나요?

**Comment by HyjK** [comment]
올바른 방식인지는 모르겠으나 makeRectangular 함수를 사용하였습니다.
음 내용상으로 어떤 ComplexNumberImpl a에 대해 a.eval(Nil) 이라는 인풋이 주어질 경우
어떻게 이해하는 것이 자연스러운지를 여쭤보고 싶었어요...! (그대로 a를 반환하는지, 아니면 모든 항에 대해 0이라고 이해해서 0의 값을 가지는 ComplexNumberSpec 객체를 리턴하는 것인지?)

**Comment by alxest** [comment]
아, 후자로 이해하시면 됩니다.
인풋 리스트에서 명시된 인자를 제외하면 계수가 0이라고 생각하시면 됩니다.
예를 들어 주석의
```(1, 0, i, -1) = 1 + (0 * x) + (i * x^2) + (-1 * x^3)```
는 풀어쓰면
```= 1 + (0 * x) + (i * x^2) + (-1 * x^3) + (0 * x^4) + (0 * x^5) + (0 * x^6) ... ```
라고 이해하시면 됩니다.
인풋 리스트가 Nil 인 경우는

```
0 + (0 * x) + (0 * x^2) + (0 * x^3) + (0 * x^4) + (0 * x^5) + (0 * x^6) ... 
= 0
```
라고 이해하시면 됩니다.

**Comment by HyjK** [comment]
감사합니다.
