### ISSUE TITLE
시험 방식에 대해서 질문이 있습니다.

### ISSUE THREAD

**Issue by greemd** [snu-sf-class/pp201602#123]
이번 숙제 7부터 sbt가 아닌 scalac를 직접 이용하는 스크립트로 빌드 및 테스트를 할 수 있게 변경되었는데요,

실제 시험에서도 숙제 7과 같이 빌드 및 실행 스크립트가 제공되는지 궁금합니다.

**Comment by alxest** [comment]
제공될 예정입니다.

**Comment by alxest** [comment]
시험 전 리허설 때 확인해보실 기회가 있을 것이고, 그때 혹시 문제가 있다면 알려주세요
