### ISSUE TITLE
hw7 구현 스타일 질문

### ISSUE THREAD

**Issue by craig1583** [snu-sf-class/pp201602#127]
add, mult 함수를 trait에서 구현하는 것과 이를 사용하는 class에서 구현하는 것이 모두 가능한데 일반적으로 어디에서 구현하는 것이 더 좋은 방법인가요?

**Comment by alxest** [comment]
이번 숙제에서는 trait에서 = ???로 되어있으니 거기서 구현하셔야 합니다.

**Comment by Ailrun** [comment]
일반적으로는 trait level 에서 사용가능한 함수들만 가고 자명하게 정의되는 함수라면 trait 위에 정의되는게 맞고, 구현이 복잡하거나 특정 구현에 의존하는 함수들은 class 에 위치하는게 맞는 것 같습니다.

숙제의 경우는 ??? 의 위치도 그렇고 실제 내용도 전자에 해당하지요.

**Comment by alxest** [comment]
저도 @Ailrun 님과 비슷한 생각
