### ISSUE TITLE
실습실 스칼라 이용문의

### ISSUE THREAD

**Issue by leegangtoe** [snu-sf-class/pp201602#13]
실습실에서 스칼라를 언제쯤 이용가능한가요?
(시험을 실습실에서 보니까 곧 환경을 구축해주시는 것 맞나요? 아니면 실습실에 별도로 설치해 주시지는 않는것인가요?)

**Comment by alxest** [comment]
아 음... 교수님과 상담해보겠습니다.

**Comment by alxest** [comment]
수업 중에 실습실은 안쓰신다고 하셔서, 따로 바쿠스에 환경 구축을 요청드리지는 않았었습니다.

**Comment by alxest** [comment]
설치하기로 하였습니다. 바쿠스에 연락해보고 경과를 공유드리겠습니다.

**Comment by alxest** [comment]
설치되었다고 합니다. 확인해보시고 경과를 알려주시겠어요? @leegangtoe
