### ISSUE TITLE
숙제 7의 채점 서버의 솔루션이 잘못된 것 같네요

### ISSUE THREAD

**Issue by Cassius99** [snu-sf-class/pp201602#131]
Spec of eval
   Input: A polynomial, represented in list of coefficients.
          For example, (1, 0, i, -1) = 1 + (0 * x) + (i * x^2) + (-1 * x^3)
   Output: Calculated result of given polynomial function with "this" as an input.
          For example, if (1 + 0*i) calls "eval" with above input, result will be
          1 + (0 * (1 + 0*i)) + (i * (1 + 0*i)^2) + (-1 * (1 + 0*i)^3)
          = 1 + 0 + i - 1
          = 0 + i

Eval 함수에서 다항식을 계산할 때 주어진 리스트에서 앞쪽의 차수가 가장 낮고 뒤쪽의 차수가 가장 높다고 되어 있는데 채점 서버의 솔루션에서는 이것과 정 반대로 리스트 앞쪽의 차수가 가장 높고 뒤쪽의 차수가 가장 낮다고 가정하고 계산하고 있습니다.
 
Default test for problem 2
Score
0
Message
Input: false, 0.09474761475885074, 0.18542610406672877, poly: List((false,0.9070775857365084,0.6538754665493768), (true,0.2080808198395575,0.9392163818968764), (false,0.6348027155523663,0.43362952474449734), (true,0.612972220096863,0.7774469375332653), (false,0.5899406304674358,0.10960375950015944), (true,0.47187697022720454,0.5149540764885183))
Solution output: Rectangular Form: (+0.5282, +0.5402), Polar Form: (+0.7556, +0.7966) (이후 생략) 
Submisson output: Rectangular Form: (+0.7270, +0.6478), Polar Form: (+0.9738, +0.7279) (이후 생략)

실제로 리스트 앞쪽이 가장 높은 차수로 가정하도록 구현을 바꿨더니 채점 서버의 솔루션과 동일한 답이 나왔습니다.

**Comment by alxest** [comment]
아... 말씀이 맞습니다. 수정했었는데 반영이 안되어있군요. 곧 수정하겠습니다.

**Comment by alxest** [comment]
수정이 반영되었습니다. 다시 시도해보시겠어요?

**Comment by Cassius99** [comment]
>>Default test for problem 2
>>Score
10
>>Message
Input: false, 0.09474761475885074, 0.18542610406672877, poly: List((false,0.9070775857365084,0.6538754665493768), (true,0.2080808198395575,0.9392163818968764), (false,0.6348027155523663,0.43362952474449734), (true,0.612972220096863,0.7774469375332653), (false,0.5899406304674358,0.10960375950015944), (true,0.47187697022720454,0.5149540764885183))
Solution output: Rectangular Form: (+0.7270, +0.6478), Polar Form: (+0.9738, +0.7279), solX: Rectangular Form: (+0.0931, +0.0175), Polar Form: (+0.0947, +0.1854), solPoly: List(Rectangular Form: (+0.7200, +0.5517), Polar Form: (+0.9071, +0.6539), Rectangular Form: (+0.2081, +0.9392), Polar Form: (+0.9620, +1.3528), Rectangular Form: (+0.5760, +0.2667), Polar Form: (+0.6348, +0.4336), Rectangular Form: (+0.6130, +0.7774), Polar Form: (+0.9900, +0.9031), Rectangular Form: (+0.5864, +0.0645), Polar Form: (+0.5899, +0.1096), Rectangular Form: (+0.4719, +0.5150), Polar Form: (+0.6985, +0.8290))
Submisson output: Rectangular Form: (+0.7270, +0.6478), Polar Form: (+0.9738, +0.7279), subX: Rectangular Form: (+0.0931, +0.0175), Polar Form: (+0.0947, +0.1854), subPoly: List(Rectangular Form: (+0.7200, +0.5517), Polar Form: (+0.9071, +0.6539), Rectangular Form: (+0.2081, +0.9392), Polar Form: (+0.9620, +1.3528), Rectangular Form: (+0.5760, +0.2667), Polar Form: (+0.6348, +0.4336), Rectangular Form: (+0.6130, +0.7774), Polar Form: (+0.9900, +0.9031), Rectangular Form: (+0.5864, +0.0645), Polar Form: (+0.5899, +0.1096), Rectangular Form: (+0.4719, +0.5150), Polar Form: (+0.6985, +0.8290))
[[PASS]]

이제 잘 되네요

**Comment by alxest** [comment]
제보 감사합니다.
