### ISSUE TITLE
hw7 스켈레톤 코드 수정 질문

### ISSUE THREAD

**Issue by dohbaek** [snu-sf-class/pp201602#133]
skeleton code에서는 trait ComplexNumberAdd와 ComplexNumberMult에 있는 function add와 mult의 리턴타입이 ComplexNumberSpec이라 되어있는데 이것을 ComplexNumberEval로 바꿔서 써도 되나요? 복소수 계산 결과값을 가지고 다시 계산을 하는게 기존 뼈대 코드를 이용하면 번거로워 이렇게 수정했습니다. 일단 기본 테스트코드와 채점서버 테스트코드에서는 잘 돌아가는 거 같은데 혹시 문제가 될까 질문 남깁니다.

gist 첨부합니다. https://gist.github.com/dohbaek/2ff9a4ccec219eea7a09b3855cc8d70d/edit

**Comment by alxest** [comment]
gist가 저에게 보이지 않습니다. private으로 되어있는지 확인해보세요.

**Comment by dohbaek** [comment]
url을 edit으로 잘못 남겨서 그런거 같은데 이것도 안 되나요? 
https://gist.github.com/dohbaek/2ff9a4ccec219eea7a09b3855cc8d70d

**Comment by alxest** [comment]
이 부분은 수정하시면 안됩니다. Add/Mult는 Eval을 모르고도 잘 정의되어야 합니다.
힌트를 드리자면 List의 함수(foldLeft/foldRight 등)를 사용하면 eval은 70자 안쪽으로 정의 가능합니다.

**Comment by dohbaek** [comment]
알겠습니다.
