### ISSUE TITLE
HW8 [A : MultOp : AddOp] 질문

### ISSUE THREAD

**Issue by Jim741305** [snu-sf-class/pp201602#134]
def eval[A : MultOp : AddOp](poly: Polynomial[A])(a: A) : A 에서

[A : MultOp : AddOp]의 의미가 무엇인가요?

**Comment by alxest** [comment]
context bound 2개가 존재한다는 것입니다.
(implicit multProxy MultOp[A])(implicit addProxy AddOp[A])의 syntactic sugar로 보시면 됩니다.
