### ISSUE TITLE
숙제7에서 아래의 eval에 관련된 테스트들에서 첫번째로 나와야하는 값이 무슨값인가요?

### ISSUE THREAD

**Issue by chickenbear** [snu-sf-class/pp201602#135]

**Comment by Ailrun** [comment]
eval 결과값입니다

**Comment by chickenbear** [comment]
나머지값들은 무엇인가요?

**Comment by Ailrun** [comment]
이슈 작성하실 때 backquote(`)나 quotation 기능(>)

관련 출력을 보여주시면 더 좋지 않을까 합니다

**Comment by Ailrun** [comment]
뒤에 연달아 나오는 값들은 다항식에 대입되는 x값, 그리고 다항식 각 항의 계수입니다.

**Comment by chickenbear** [comment]
감사합니다.  그런데 위의  'backquote(`)나 quotation 기능(>) 관련 출력을 보여주시면 더 좋다'라는 말이 무슨뜻인가요?

**Comment by Ailrun** [comment]
오타가 있어 수정했습니다. Github 이슈에는 여러 기능들이 있고, 기능들을 활용해서 이슈를 작성해주시면 답변이 보다 용이할 거라는 이야기였습니다.

예를 들면 다음과 같습니다.

```
"이것은 backquote 를 위 아래에 3 개씩 사용한 코드 블록입니다."
```

> 이것은 (>)를 사용한 인용 블록입니다.

이것은 `backquote` 를 앞/뒤에 하나씩 사용한 한 줄 코드입니다.

**Comment by chickenbear** [comment]
아 네 감사합니다. 참고하겠습니다.

**Comment by Ailrun** [comment]
이 경우에는 *아래의 eval* 에 해당하는 출력을 작성해주시고, 궁금한 부분을 따로 `인라인`으로 작성해주셨다면 답변하기 보다 편하지 않았을까... 하는 이야기입니다.
