### ISSUE TITLE
숙제7의 채점코드가 업데이트가 안 된 것 같습니다.

### ISSUE THREAD

**Issue by qpzm** [snu-sf-class/pp201602#136]
#131 숙제7 의 오류가 수정되었다고 하셨는데
채점결과가 아래와 같이 그대로여서 질문드립니다.

>Default test for problem 2
Score
0
Message
Input: false, 0.09474761475885074, 0.18542610406672877, poly: List((false,0.9070775857365084,0.6538754665493768), (true,0.2080808198395575,0.9392163818968764), (false,0.6348027155523663,0.43362952474449734), (true,0.612972220096863,0.7774469375332653), (false,0.5899406304674358,0.10960375950015944), (true,0.47187697022720454,0.5149540764885183))
Solution output: Rectangular Form: (+0.5282, +0.5402), Polar Form: (+0.7556, +0.7966), solX: Rectangular Form: (+0.0931, +0.0175), Polar Form: (+0.0947, +0.1854), solPoly: List(Rectangular Form: (+0.7200, +0.5517), Polar Form: (+0.9071, +0.6539), Rectangular Form: (+0.2081, +0.9392), Polar Form: (+0.9620, +1.3528), Rectangular Form: (+0.5760, +0.2667), Polar Form: (+0.6348, +0.4336), Rectangular Form: (+0.6130, +0.7774), Polar Form: (+0.9900, +0.9031), Rectangular Form: (+0.5864, +0.0645), Polar Form: (+0.5899, +0.1096), Rectangular Form: (+0.4719, +0.5150), Polar Form: (+0.6985, +0.8290))
Submisson output: Rectangular Form: (+0.7270, +0.6478), Polar Form: (+0.9738, +0.7279), subX: Rectangular Form: (+0.0931, +0.0175), Polar Form: (+0.0947, +0.1854), subPoly: List(Rectangular Form: (+0.7200, +0.5517), Polar Form: (+0.9071, +0.6539), Rectangular Form: (+0.2081, +0.9392), Polar Form: (+0.9620, +1.3528), Rectangular Form: (+0.5760, +0.2667), Polar Form: (+0.6348, +0.4336), Rectangular Form: (+0.6130, +0.7774), Polar Form: (+0.9900, +0.9031), Rectangular Form: (+0.5864, +0.0645), Polar Form: (+0.5899, +0.1096), Rectangular Form: (+0.4719, +0.5150), Polar Form: (+0.6985, +0.8290))
[[FAIL]]

**Comment by alxest** [comment]
submission id를 알려주세요

**Comment by qpzm** [comment]
Submission 1281입니다

**Comment by alxest** [comment]
이건 업데이트 전에 제출하신거라 반영이 안되어있습니다.

**Comment by alxest** [comment]
재채점 돌려두었습니다.

**Comment by qpzm** [comment]
제가 착각했네요. 감사합니다!
