### ISSUE TITLE
숙제 08 identity 질문

### ISSUE THREAD

**Issue by gdw0809** [snu-sf-class/pp201602#139]
숙제 08에서 identity의 정의가
Identity: for all element a of type A, op(identity, a) = identity로 되어 있는데,
op(identity, a) = a가 되어야 하지 않나요?

**Comment by alxest** [comment]
네 맞습니다, 수정해서 푸시하겠습니다.

**Comment by gdw0809** [comment]
네 감사합니다!

**Comment by norangLemon** [comment]
submodule commit 번호도 수정해주세요.
이전 커밋 번호로 되어있습니다
