### ISSUE TITLE
숙제 8번의 Complex Number에 대해서 질문이 있습니다.

### ISSUE THREAD

**Issue by greemd** [snu-sf-class/pp201602#140]
Complex Number에 보면
  /*
   ComplexNumber class and its companion object ported from hw07.
   */
라는 설명이 있는데요, 그러면 hw08에 맞게 07의 내용을 porting하기 위해서, 새로운 class와 object등을 만들어도 되는건가요? 즉 ??? 이외의 부분에 수정을 해도 되는지 궁금합니다.

**Comment by alxest** [comment]
지금은 내용이 비어있는데 내용을 수정하시면 댓글을 달아서 저한테 푸시 알람을 한번 더 주세요

**Comment by greemd** [comment]
@alxest 내용 수정하였습니다.

**Comment by alxest** [comment]
일단 의도한 구현은 새로운 class/object를 정의하지 않습니다.
새로운 class/object를 정의하는게 어떻게 도움이 될 지 감이 안오는데, 좀 더 구체적으로 적어주시겠어요? 다른 학생들이 보면 안될만한 내용이면 메일로 보내주셔도 됩니다.

**Comment by greemd** [comment]
@alxest  아, 제가 문제를 잘못 이해하고 있었네요ㅠ
답변 감사합니다.
