### ISSUE TITLE
숙제 8번 object Polynomials 관련 질문(2가지) 드립니다.

### ISSUE THREAD

**Issue by HyjK** [snu-sf-class/pp201602#141]
1. 이 주석이 의미하는 바가 무엇인가요 ? (object Polynomials 정의 직전 구문)
> /*
>  In actual test, we may use types other than complex numbers.
>   */

2. implicitly[MultOp[Polynomial[A]]].op 라는 연산이 어떤 식으로 정의되는지 잘 이해가 되지 않습니다. 

>  val poly = List(1.0, 1.0, 1.0, 1.0)
> println(implicitly[MultOp[Polynomial[Real]]].op(poly, poly)) 
라는 테스트 케이스에서 주석에 어떤 값이 나와야 하는지 힌트가 주어져 있지 않아 혼란스러워서 드리는 질문입니다. 

예를 들어 (a + b*x + c*x^2) 라는 Polynomial[A]와 (A + B*x + C*x^2) 라는 Polynomial[A] 사이 곱셈을 한다고 하면 

(a + b*x + c*x^2)*(A + B*x + C*x^2) 
= a*A + (a*B+b*A)*x+ (a*C + b*B+ c*A)*x^2 + (a*C + c*A)* x^3 + c*C*x^4

이므로 List(a*A, (a*B+b*A), (a*C + b*B+ c*A), (a*C + c*A), c*C)가 반환되어야 하나요?

**Comment by dohbaek** [comment]
조교님이 답변을 아직 안 해주셔서 제가 아는 바로 혹시 도움이 될까 남기자면요.

1. Polynomial 구현 시 Complex를 갖고 구현(e.g. Polynomial[Complex])로 구현하지 말고 generic하게(e.g. Polynomial[A])하게 구현하라는 말씀이신 거 같습니다. 궁금해서 complex number 외의(real number가 complex number에 포함된다 생각하면)  coefficient를 갖는 polynomial이 있나 찾아보고는 있는데 저는 찾지는 못하겠네요... 그렇지만 Polynomial[Real]을 구현한다 쳐도 generic하게 구현하는게 필요하지 않나 싶습니다.

2. 이해하신 바가 맞는 거 같습니다. 그래서 skeleten code line 81의 println값이 List(1.0, 2.0, 3.0, 4.0, 3.0, 2.0, 1.0)라고 나오면 되는 거 같습니다. (1 + x + x^2 + x^3)^2 = (1 + 2x + 3x^2 + 4x^3 + 3x^4 + 2x^5 + x^6)

**Comment by Ailrun** [comment]
@dohbaek 그냥 간단하게 quaternion Polynomial을 생각하셔도 되고, Matrix를 생각할 수도 있지요.
또, 꼭 수가 아니더라도 String 도 Polynomial 같이 생각할 수 있습니다. (*와 +를 모두 Concatenate로 취급)

1. Complex 뿐만이 아니라 곱하기/더하기가 정의될 수 있는 모든 것들에 대해서 Polynomial이 동작해야 한다는 의미입니다. Naive 하게 구현하지 말란 뜻이죠.

2. 일반적인 Polynomial 곱셈을 말합니다.

**Comment by alxest** [comment]
윗 댓글들이 맞습니다. 댓글 감사합니다.

**Comment by HyjK** [comment]
@dohbaek  @Ailrun @alxest  모두 도움이 많이 되었습니다. 감사합니다!!!
