### ISSUE TITLE
과제 6,7 모범답안을 올려주실 수 있나요?

### ISSUE THREAD

**Issue by leegangtoe** [snu-sf-class/pp201602#143]
과제 6,7 모범답안을 올려주실 수 있나요?

**Comment by alxest** [comment]
과제 7은 8과 관련이 있어서 지금은 못올려드리고, 8 데드라인이 끝나고 한번 더 푸시를 주시면 그때 올려드리겠습니다.

**Comment by alxest** [comment]
https://github.com/snu-sf-class/pp201602/issues/146

**Comment by HyjK** [comment]
조교님, 7, 8번 과제 모범답안 올려주시면 공부하는데 도움이 많이 될 것 같습니다.
바쁘신 줄 알지만 부탁 드릴게요!

**Comment by alxest** [comment]
올렸습니다: https://github.com/snu-sf-class/pp201602/issues/162
