### ISSUE TITLE
숙제 8번 주석 질문

### ISSUE THREAD

**Issue by jeuxdeau** [snu-sf-class/pp201602#144]
안녕하세요.
data.scala의 아래 부분을 보고 질문 드립니다.
`  /*
   You should not call this constructor directly.
   You should implement and use makeRectangular, makePolar in Complex object.
   */`
makeRectangular와 makePolar 함수 안에서도 저 constructor를 쓰면 안 되나요?
감사합니다.

**Comment by dohbaek** [comment]
제가 makeRectangular와 makePolar 함수 안에서 Complex의 constructor을 쓴 코드를 갖고 조교님께 오늘 질문을 했는데 별 말씀이 없으신 걸로 보아 써도 될 거 같습니다.

**Comment by leegangtoe** [comment]
그런데 makeRectangular와 makePolar안에 constructor를 안쓰면 다른 방법이 있나요?? 안쓰고는 불가능한 것 같은데..

**Comment by Ailrun** [comment]
그 안에서는 구현할 수 있는 다른 방법이 없습니다. Constructor 를 어디에서도 안 쓰면 Class 를 Construct 할 방법이 없지요.

**Comment by jeuxdeau** [comment]
답변 모두 감사드립니다.

**Comment by alxest** [comment]
윗 댓글들 감사드립니다. 말씀하신 것처럼 mkRectangular/mkComplex 에서는 new를 쓰셔도 되고, 이외의 곳에서는 쓰시면 안됩니다. 곧 주석 업데이트하여 푸시하겠습니다.

**Comment by alxest** [comment]
수정해서 푸시했습니다.
