### ISSUE TITLE
숙제 8번 질문

### ISSUE THREAD

**Issue by frmh0313** [snu-sf-class/pp201602#145]
혹시 polynomialMultProxy를 정의할 때 polynomialAddProxy를 사용해도 괜찮나요? 아니면 polynomialAddProxy와는 상관없이 필요한 기능이 전부 polynomialMultProxy 내부에 구현이 되어 있어야 하나요?

**Comment by Ailrun** [comment]
어떤 A 타입에 대해 Polynomial Add가 정의되어 있어야 A 타입에 대해 Polynomial Multiply 가 가능하겠지요.

A 타입이 무언가를 보장한다면 (이를테면 Complex Number 의 원소들이 Real 이고, 이들이 Add와 Multiply를 구현하는 것 같이) 그것은 이후의 구현에서 사용해도 되는 겁니다.

물론 어떤 특정한 값에 대해서만 성립하는 것 (예를 들면 A 타입이 .real 을 가진다고 가정하는 것) 같은 것은 구현에서 사용하면 안되겠지요.

**Comment by alxest** [comment]
사용하셔도 괜찮습니다.

**Comment by frmh0313** [comment]
네 감사합니다.
