### ISSUE TITLE
중간고사 5번을 새로 푸는 과정에서, 궁금한 점이 생겼습니다.

### ISSUE THREAD

**Issue by sangjaekang** [snu-sf-class/pp201602#148]
abstract class Iter[A] {
    def getValue: Option[A]
    def getNext: Iter[A]
}

  abstract class BiIter[A] extends Iter[A] {
    def getNext: BiIter[A]
    def getPrev: BiIter[A]
  }

  sealed abstract class Prime[Int] extends BiIter[Int] {
    def getValue : Option[Int]
    def getNext : Prime[Int]
    def getPrev : Prime[Int]
  }

  case class Empty[Int] extends Prime[Int] {
    def getValue : Option[Int] = None
    def getPrev : Prime[Int] = this
    def getNext : Prime[Int] = new PrimeIter[Int](this, **nextPrime(1)**)
  }

  case class PrimeIter[Int](val prev : Prime[Int],val current : Int) extends Prime[Int] {
    def getValue : Option[Int] = Some(current)
    def getNext : Prime[Int] = new PrimeIter[Int](this, **nextPrime(current)**) 
    def getPrev : Prime[Int] = prev
  }

PrimeIter의 def getNext를 구현하려고 했을 때, nextPrime(current) 부분이 
type mismatch, expected : Int, real : Int
로 뜹니다. 

expected와 real의 type이 같은데 왜 type mismatch가 뜨는지 이유가 궁금합니다

**Comment by alxest** [comment]
https://github.com/snu-sf-class/pp201602/issues/93
