### ISSUE TITLE
숙제 Due와 관련하여 여쭤볼 것이 있습니다.

### ISSUE THREAD

**Issue by eipi100303** [snu-sf-class/pp201602#149]
이전 과제(7번)까지 듀가 10일, 혹은 그 이상이었는데

8번부터 딜레이 없이 10일 미만이라서 (8일, 6일)

이틀 정도 듀 기간을 늘려주실 수 있나요?

이전에 교수님께서 10일 정도 주신다고 말씀하신 것을 들어서 (학기 초반)

혹시 듀를 연장해주실 수 있으신지 여쭤보고 싶습니다.

**Comment by alxest** [comment]
듀는 교수님께서 결정하시니, 교수님께 여쭤보시기 바랍니다.
