### ISSUE TITLE
강의 자료

### ISSUE THREAD

**Issue by jeuxdeau** [snu-sf-class/pp201602#15]
안녕하세요.
강의 슬라이드를 수업 전에 올려주실 수 있는지 궁금합니다. 멀리서 화면이 잘 보이지 않아서요.
감사합니다.

**Comment by alxest** [comment]
교수님께 문의드리겠습니다.

**Comment by alxest** [comment]
교수님께서 그건 어렵다고 하셨습니다. 수업 중에 글자 크기를 최대한 키우겠다고 하셨습니다.

**Comment by jeuxdeau** [comment]
네, 감사합니다. 수업 후 업데이트도 부탁드려요.

**Comment by alxest** [comment]
예, 업데이트 했습니다.
