### ISSUE TITLE
(숙제8) polynomialAddProxy.identity의 값 관련

### ISSUE THREAD

**Issue by minsuu** [snu-sf-class/pp201602#150]
```
>>Default test for problem 12
>>Score
0
>>Message
polynomialAddProxy.identity
Solution output: List(0)
Submisson output: List()
[[FAIL]]
```

이런 메시지를 받았는데요 ㅠㅠ 고쳐서 다시 내긴 했는데, `polynomialAddProxy.identity`가 `Nil`이어선 안되는 이유가 있을까요..? 제 구현상에서는 polynomial add/multi 연산에서 각 polynomial이 Nil로 들어올 때에도 작동해서 괜찮다고 생각했었거든요..

**Comment by alxest** [comment]
말씀이 맞습니다. 제 실수입니다. 수정하고 재채점하겠습니다.

**Comment by minsuu** [comment]
감사합니다~

**Comment by alxest** [comment]
스크립트가 제대로 바뀌었는지 확인을 위해 submission ID를 알려주세요.

**Comment by minsuu** [comment]
submission id는 1469이나, 한시간째 pending상태로 있군요ㅠㅠ

**Comment by alxest** [comment]
지금은 재채점이 되어있습니다. 확인해보니 둘 다 success로 뜹니다.

**Comment by minsuu** [comment]
감사합니다!
