### ISSUE TITLE
과제 9에서 ~~PrintAll 함수에 대한 질문

### ISSUE THREAD

**Issue by Cassius99** [snu-sf-class/pp201602#152]
나머지는 다 구현했는데 여기서 막히네요
입력이 List(Object)라서 Object를 SNUMember, Professor, Student로 바꿔줄 proxy가 필요한 것 같은데 어떻게 구현해야 할지 모르겠습니다. 아니면 제가 잘못 생각하고 있는 건가요?

**Comment by alxest** [comment]
입력이 List(Object)라는 부분을 다시 생각해보세요.
슬라이드 참조하시고 슬라이드 코드의 타입을 확인해보시면 도움이 될 듯 합니다.

**Comment by Cassius99** [comment]
Dynamic Dispatch를 써서 해결했습니다. 답변 감사합니다.
