### ISSUE TITLE
과제 8 숙제 제출 채점에 질문이 있습니다.

### ISSUE THREAD

**Issue by sangjaekang** [snu-sf-class/pp201602#153]
>>Default test for problem 11
>>Score
0
>>Message
polynomialMultProxy.op Input: List(406937919, -888301832, 796399098) List(-1800014724, 326475673, -399098706)
Solution output: List(1038493316, -1525301305, 580848674, 1486628090, -1686009876)
Submisson output: List(212005032, 70450231, 1787092178)
[[FAIL]]
가 뜨는데, polynomialMultProxy.op의 구현이

(a0 * x^0 + a1 * x^1 + a2 * x^2 ) * (b0 * x^0 + b1 * x^1 + b2 * x^2 ) = a0 *b0 * x^0 + (a0 *b1 + a1 *b0) *x^1 + ...........................

식으로의 구현이 아닌가요?
a0 = 406937919
a1 = -888301832
a2 = 796399098

b0 = -1800014724
b1 = 326475673
b2 = -399098706
이라고 생각하고 손으로 계산해보아도, solution output과 다른 답이 나오길래 질문 올립니다.

**Comment by Ailrun** [comment]
일단 제출하신게 맞을 수는 없는게, 항이 적어도 5개가 나와야하는데 항이 3개 뿐이네요.
