### ISSUE TITLE
hw9 3번 문제 질문

### ISSUE THREAD

**Issue by craig1583** [snu-sf-class/pp201602#156]
OOP output:           雿揑伟ኦ剟  [326475673]
          Ⲗ虰氚齼廮  [1862424634]:    Mean Lecture Eval = NaN
          羀ᙾ㝺帬蠗  [470744525]
          撨溔귥啧ᴐ  [1118391289]:           Mean Grade = NaN
          ᒺ툟柅垂ब  [-1360886330]
          屹꘷䪨睅湀  [-1616852884]:    Mean Lecture Eval = 5.00
          쓱㖦ꄑ쨡祓  [-1287444256]
          늒⎟쐡㢞퀱  [1445393281]:    Mean Lecture Eval = 1.67
          ⭎㮐䝦必㸽  [-1925025441]:           Mean Grade = 2.63
          Ⴐ⨊᱁峑䢬  [521223985]
          樄垥캝晖õ  [-1122632041]:           Mean Grade = NaN
          縼갊㺅酜䢤  [362880136]:    Mean Lecture Eval = 1.67
          ᇡ⬕흯ъ홿  [-2012554983]:           Mean Grade = 1.80
          ٌ㴤瓰滍們  [1565803629]:    Mean Lecture Eval = 2.00
          咉茭铙楞錺  [-1217343505]:    Mean Lecture Eval = 3.00
          㴇/䷭푞횊  [-730502156]:           Mean Grade = 2.63
          瘁遍祿拔ॖ  [-1178915750]:           Mean Grade = 2.97
          ฃ惖蘤錴托  [-2124083343]
          ㅂ翭ꍐ쒻䠼  [-842583396]:           Mean Grade = 2.30
          頊䊑蘸곘䨅  [1826552044]:           Mean Grade = 2.97
TOP output:           瀕洠今㑹ℛ  [-1119911334]:           Mean Grade = 2.55
          揪燣眥⸂ω  [1192961608]:    Mean Lecture Eval = 5.00
          ꡑ➼섍俳厄  [-387446408]:           Mean Grade = 2.55
          ᐮ왧捅嶕德  [1427676170]:           Mean Grade = 3.55
          䘞娮躞빤玫  [1468676121]:           Mean Grade = 2.30
          疾世텃䉑뮊  [1983993227]
          Ȉ鶔甚낮⛅  [-1392372005]:    Mean Lecture Eval = 3.00
          烿廠鹙ઇಯ  [-2027623099]:           Mean Grade = 2.30
          챞̤攗쀡曨  [-1073772079]:           Mean Grade = 3.30
          앙ꎏ썘曉鲽  [1497756987]:           Mean Grade = 1.30
          閭ᮔꎜ翝珃  [1946675151]:           Mean Grade = 4.30
          柳堀驟鿦藏  [-314045670]:    Mean Lecture Eval = 5.00
          ᑔ쭠ế⥒ഏ  [-1150427548]:    Mean Lecture Eval = NaN
          ꩆ뙺࠼鍫倹  [-1411440793]:           Mean Grade = NaN
          리㯒깎뱵҅  [1060986031]:    Mean Lecture Eval = 4.00
          Ჟᴝ绝皋겴  [1214153140]:           Mean Grade = NaN
          뇖痞犀棕꼳  [1558521076]
          掯췴樴윺꺒  [561651670]:           Mean Grade = 3.30
          뙶ဦ릇ल묦  [1522285199]:           Mean Grade = 3.80
          䓈麁쀕흁쮊  [1955766398]:           Mean Grade = 2.97

결과가 이렇게 출력되어 Fail이 뜨는데 혹시 두 함수에 서로 다른 list가  input으로 들어간 건 아닌가요? 출력된 이름과 타입이 달라서 여쭤봅니다.

**Comment by alxest** [comment]
submission id를 알려주세요

**Comment by craig1583** [comment]
1501입니다.

**Comment by alxest** [comment]
@craig1583 말씀이 맞습니다, 곧 수정해서 푸시하겠습니다.

**Comment by alxest** [comment]
그리고 모든 분에게 reminder: https://github.com/snu-sf-class/pp201602/issues/151

**Comment by alxest** [comment]
@craig1583 수정해서 푸시했습니다.

**Comment by alxest** [comment]
@craig1583 지금 기본 테스트 fail 뜨는건 newline 때문으로 생각됩니다.
제가 이 이슈에서 https://github.com/snu-sf-class/pp201602/issues/151 수정하는 커밋을 올리고, 직후에 다시 한번 더 수정하여 그 커밋을 덮어썼는데, 수정 커밋을 그 짧은 순간에 확인하신 것 같습니다.
로직을 간단하게 하기 위해 xs.foldLeft("")((s, i) => s + i.prettyPrint + "\n") 이렇게 수정했습니다.

**Comment by HyjK** [comment]
조교님 submission ID 1515 번 확인 부탁 드립니다. 방금 말씀하신 부분과 관련있는 에러인 것 같은데 어디가 다른지 정확히 모르겠네요 ㅠ!

**Comment by craig1583** [comment]
OOP output:           雿揑伟ኦ剟  [326475673]
          Ⲗ虰氚齼廮  [1862424634]:    Mean Lecture Eval = NaN
          羀ᙾ㝺帬蠗  [470744525]
          撨溔귥啧ᴐ  [1118391289]:           Mean Grade = NaN
          ᒺ툟柅垂ब  [-1360886330]
          屹꘷䪨睅湀  [-1616852884]:    Mean Lecture Eval = 5.00
          쓱㖦ꄑ쨡祓  [-1287444256]
          늒⎟쐡㢞퀱  [1445393281]:    Mean Lecture Eval = 1.67
          ⭎㮐䝦必㸽  [-1925025441]:           Mean Grade = 2.63
          Ⴐ⨊᱁峑䢬  [521223985]
          樄垥캝晖õ  [-1122632041]:           Mean Grade = NaN
          縼갊㺅酜䢤  [362880136]:    Mean Lecture Eval = 1.67
          ᇡ⬕흯ъ홿  [-2012554983]:           Mean Grade = 1.80
          ٌ㴤瓰滍們  [1565803629]:    Mean Lecture Eval = 2.00
          咉茭铙楞錺  [-1217343505]:    Mean Lecture Eval = 3.00
          㴇/䷭푞횊  [-730502156]:           Mean Grade = 2.63
          瘁遍祿拔ॖ  [-1178915750]:           Mean Grade = 2.97
          ฃ惖蘤錴托  [-2124083343]
          ㅂ翭ꍐ쒻䠼  [-842583396]:           Mean Grade = 2.30
          頊䊑蘸곘䨅  [1826552044]:           Mean Grade = 2.97
TOP output:           雿揑伟ኦ剟  [326475673]
          Ⲗ虰氚齼廮  [1862424634]:    Mean Lecture Eval = NaN
          羀ᙾ㝺帬蠗  [470744525]
          撨溔귥啧ᴐ  [1118391289]:           Mean Grade = NaN
          ᒺ툟柅垂ब  [-1360886330]
          屹꘷䪨睅湀  [-1616852884]:    Mean Lecture Eval = 5.00
          쓱㖦ꄑ쨡祓  [-1287444256]
          늒⎟쐡㢞퀱  [1445393281]:    Mean Lecture Eval = 1.67
          ⭎㮐䝦必㸽  [-1925025441]:           Mean Grade = 2.63
          Ⴐ⨊᱁峑䢬  [521223985]
          樄垥캝晖õ  [-1122632041]:           Mean Grade = NaN
          縼갊㺅酜䢤  [362880136]:    Mean Lecture Eval = 1.67
          ᇡ⬕흯ъ홿  [-2012554983]:           Mean Grade = 1.80
          ٌ㴤瓰滍們  [1565803629]:    Mean Lecture Eval = 2.00
          咉茭铙楞錺  [-1217343505]:    Mean Lecture Eval = 3.00
          㴇/䷭푞횊  [-730502156]:           Mean Grade = 2.63
          瘁遍祿拔ॖ  [-1178915750]:           Mean Grade = 2.97
          ฃ惖蘤錴托  [-2124083343]
          ㅂ翭ꍐ쒻䠼  [-842583396]:           Mean Grade = 2.30
          頊䊑蘸곘䨅  [1826552044]:           Mean Grade = 2.97

[[FAIL]]
눈으로보기엔 일치하는 결과인 것 같은데 어떻게 고쳐야 할까요?

**Comment by alxest** [comment]
아아 잠시만요!

**Comment by alxest** [comment]
채점 스크립트에서 끝에 newilne을 안넣어줬었는데 수정해서 재채점 돌려놨습니다.

**Comment by craig1583** [comment]
넵 PASS 떴습니다

**Comment by HyjK** [comment]
감사합니다 :)

**Comment by wlals31** [comment]
안녕하세요, 조교님
submission id 1623 한 번 확인해 주시겠어요?
newline이 반영된 코드인데 3번에서 눈으로 볼 때는 똑같은데 Fail이 뜨네요 ㅠㅠ

**Comment by alxest** [comment]
@wlals31 제가 처음 스켈레톤 코드를 올렸을 때 오타가 있었는데, 그 상황에서 작업하신 듯 합니다.
https://github.com/snu-sf-class/pp201602-hw-09/commit/746c7109094d215c939ea7c3012ae8234c4ea4b1

**Comment by alxest** [comment]
캠릿브지 대학의 연결구과에 따르면...
