### ISSUE TITLE
[질문] 숙제 1 관련

### ISSUE THREAD

**Issue by SeungyuLee** [snu-sf-class/pp201602#16]
안녕하세요 PP 수강생입니다
과제 1번 PPascal  문제에서 과제 수정전에  tail recursion으로 풀어야한다는 지시가 있었던 것 같은데
과제가 수정되면서 바뀐건가요? 그러면 그냥 자유롭게 일반 recursion으로 풀어도 되는지 궁금합니다
감사합니다.

**Comment by alxest** [comment]
아, 수정 전에도 그런 요구 사항은 없었습니다. PPascal 문제는 tail recursion 없이 푸셔도 됩니다.
