### ISSUE TITLE
과제9관련 질문입니다.

### ISSUE THREAD

**Issue by chickenbear** [snu-sf-class/pp201602#164]
Submission 1756번 입니다.

3번쨰 테스트케이스에서 틀린 이유를 알 수 있을까요? 

다 깨져서 나와서 읽을수가 없어서요.

감사합니다.

**Comment by Gwangwon-Choi** [comment]
Submission 1772번입니다. 저도 틀린 이유를 알고 싶습니다.
감사합니다.

**Comment by timedilation** [comment]
만약에 결과가
Ⲗ虰氚齼廮  [1862424634]:    Mean Lecture Eval = NaN
이런식으로 나오는것이라면 맨 앞에 깨진 글자들이 name이라고 생각하고 OOP output이랑 TOP output을 비교하면서 보시면될것같아요!

**Comment by chickenbear** [comment]
혹시 아래와같이 아무것도 출력되지않는 것을 경험하신분이 있을까요?
계속 이렇게나오는데 원인을 못찾겠네요
OOP output:           雿揑伟ኦ剟  [326475673]
          Ⲗ虰氚齼廮  [1862424634]:    Mean Lecture Eval = NaN
          羀ᙾ㝺帬蠗  [470744525]
          撨溔귥啧ᴐ  [1118391289]:           Mean Grade = NaN
          ᒺ툟柅垂ब  [-1360886330]
          屹꘷䪨睅湀  [-1616852884]:    Mean Lecture Eval = 5.00
          쓱㖦ꄑ쨡祓  [-1287444256]
          늒⎟쐡㢞퀱  [1445393281]:    Mean Lecture Eval = 1.67
          ⭎㮐䝦必㸽  [-1925025441]:           Mean Grade = 2.63
          Ⴐ⨊᱁峑䢬  [521223985]
          樄垥캝晖õ  [-1122632041]:           Mean Grade = NaN
          縼갊㺅酜䢤  [362880136]:    Mean Lecture Eval = 1.67
          ᇡ⬕흯ъ홿  [-2012554983]:           Mean Grade = 1.80
          ٌ㴤瓰滍們  [1565803629]:    Mean Lecture Eval = 2.00
          咉茭铙楞錺  [-1217343505]:    Mean Lecture Eval = 3.00
          㴇/䷭푞횊  [-730502156]:           Mean Grade = 2.63
          瘁遍祿拔ॖ  [-1178915750]:           Mean Grade = 2.97
          ฃ惖蘤錴托  [-2124083343]
          ㅂ翭ꍐ쒻䠼  [-842583396]:           Mean Grade = 2.30
          頊䊑蘸곘䨅  [1826552044]:           Mean Grade = 2.97

TOP output:           雿揑伟ኦ剟  [326475673]
          Ⲗ虰氚齼廮  [1862424634]
          羀ᙾ㝺帬蠗  [470744525]
          撨溔귥啧ᴐ  [1118391289]
          ᒺ툟柅垂ब  [-1360886330]
          屹꘷䪨睅湀  [-1616852884]
          쓱㖦ꄑ쨡祓  [-1287444256]
          늒⎟쐡㢞퀱  [1445393281]
          ⭎㮐䝦必㸽  [-1925025441]
          Ⴐ⨊᱁峑䢬  [521223985]
          樄垥캝晖õ  [-1122632041]
          縼갊㺅酜䢤  [362880136]
          ᇡ⬕흯ъ홿  [-2012554983]
          ٌ㴤瓰滍們  [1565803629]
          咉茭铙楞錺  [-1217343505]
          㴇/䷭푞횊  [-730502156]
          瘁遍祿拔ॖ  [-1178915750]
          ฃ惖蘤錴托  [-2124083343]
          ㅂ翭ꍐ쒻䠼  [-842583396]
          頊䊑蘸곘䨅  [1826552044]

**Comment by alxest** [comment]
꺠져서 나와서 못 읽는다는건 말이 안됩니다.

**Comment by alxest** [comment]
구현을 잘못하셔서 그런거고 출력에서 명백하게 알 수 있습니다.
