### ISSUE TITLE
과제 9번 문의드립니다.

### ISSUE THREAD

**Issue by Gwangwon-Choi** [snu-sf-class/pp201602#165]
문제에 나와있는게
snuMemberUglyPrint 함수를 dynamic dispatch를 쓰지 말고
snuMemberUglyPrint(gil: SNUMember)에서는 SNUMember 에 prettyPrint를,
snuMemberUglyPrint(gil)에서는 Professor의 prettyPrint를 사용하라는 말 맞나요?
제가 문제를 잘 못 이해한 것인가 싶어서요..

**Comment by HyjK** [comment]
맞게 이해하신 것 같아요. dynamic dispatch를 쓴다면 명시해준 타입(첫 줄의 SNUMember)와 관계 없이 스스로의 타입을 Professor로 알고 있기 대문에 매번 
> >>>>        Gil Hur  [00000]:    Mean Lecture Eval = 5.00
를 출력합니다. 
그렇지만 static dispatch 를 쓰면 SNUMember 타입의 prettyPrint를 써서 최종적으로 기본 테스트케이스에서 아래와 같이 출력하면 맞는 것 같아요. 

''' >>>>        Gil Hur  [00000]
''' >>>>        Gil Hur  [00000]:    Mean Lecture Eval = 5.00

**Comment by alxest** [comment]
예 두분의 말씀이 맞습니다.
