### ISSUE TITLE
과제 제출에 관한 공지가 어디있나요?

### ISSUE THREAD

**Issue by Gwangwon-Choi** [snu-sf-class/pp201602#17]
GitHub 처음이라서.. Issues 찾아보니까 수요일에 공지 해주신다고 하셨는데 공지가 어디있는지 몰라서 과제 제출을 아직 못했습니다.. 
죄송하지만 어디있는지 알려주실 수 있을까요?

**Comment by alxest** [comment]
늦어져서 죄송합니다. 제출 사이트 만드는 작업을 마무리 중에 있습니다...
