### ISSUE TITLE
server VM warning 이 채점에 문제가 될 수 있는지 질문 드립니다.

### ISSUE THREAD

**Issue by HyjK** [snu-sf-class/pp201602#18]
안녕하세요!
IntelliJ IDE에서 sb t run / test를 돌리면 다음과 같은 문구가 나옵니다.
"Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0"
warning이 뜨기는 하는데 실행에는 큰 문제가 없는 것 같아서 질문 드립니다. 
혹시 채점 서버에서 문제가 생길 수 있을까요?

그리고 하나 덧붙여 질문을 드리자면 scala를 IDE에서 컴파일하고 실행하는건 원래 느린 편인가요?
첫 숙제 파일을 컴파일하고 실행해보면 run 명령어에 6~8초, test에 8~11초 정도 쓰는 것 같고 test에서 run 자체는 밀리세컨드 단위로 마무리가 되는 것 같은데 이 정도면 어느 정도로 빠르고 느린 것인지 전혀 모르겠어서 여쭙습니다.
( Run completed in 252 milliseconds.)
만일 문제가 될 정도로 느린 것이라면, 채점 서버 기준으로 보통 어느 정도에 마무리되어야 하는지도 말씀해주시면 정말 감사하겠습니다 :)

**Comment by alxest** [comment]
안녕하세요, 
- sbt warning은 숙제 기본 템플릿을 받아서 했을 때 나오는 문구인가요? 한번 확인 부탁드립니다.
- run/test 돌릴 때 매번 컴파일을 다시 해서 그런 것 같습니다. sbt를 한번 띄워놓고, (commandline 에서 sbt 라고 치면 됩니다) 거기서 계속 진행하면, 매번 컴파일하지 않을 듯 합니다. sbt 띄우고 compile 이라고 한번 쳐보시고, 그 다음에 run/test 를 치시면 시간이 대충 어떻게 걸리시나요?
- 테스트의 경우에 대해서는, 일단 시간을 넉넉히 주고 돌릴 예정입니다. "컴파일만 했을 때 걸리는 시간 + 5초" 정도로 돌릴 예정인데요, 이 정도면 아마도 시간복잡도 자체가 차이나지 않는 이상 시간 문제는 없으리라 생각합니다. (그리고 시간복잡도 자체가 차이나는 경우는 걸러지리라 생각합니다.) 혹시 알고리즘이 스펙에 맞게 (fibB의 예를 들면, linear 하게) 짜여졌는데도 시간 문제가 생긴다면 claim 을 받도록 하겠습니다.

**Comment by jeuxdeau** [comment]
안녕하세요.
저도 같은 종류의 warning이 뜹니다. 문구는 "Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0"입니다. 숙제 기본 템플릿을 사용하였고, 컴파일, 실행, 테스트 등에는 문제가 없었습니다.
감사합니다.

**Comment by HyjK** [comment]
감사합니다 :)
* 숙제 기본 템플릿을 받아서 사용하고 있습니다. 중간에 숙제가 업데이트 된 이후에 다시 s bt를 넣어서 사용하긴 했으나 전후에 동일하게 발생합니다.
* 기존에 s bt run / s bt test만 사용하였어서 많이 느렸던 것 같네요! 말씀하신 대로 해보니 처음 컴파일에는 시간이 조금 걸렸던 것 같은데(5초) 이후 run/test는 0~3초 안으로 나오는 것 같습니다. 감사합니다!!!

**Comment by alxest** [comment]
과제 채점에 sbt 를 사용하지 않게 되었습니다.
https://github.com/snu-sf-class/pp201602/issues/25
