### ISSUE TITLE
출석 관련 공지

### ISSUE THREAD

**Issue by kim-yoonseung** [snu-sf-class/pp201602#19]
안녕하세요 수업 조교입니다.

이번 수업도 그랬지만 다음 수업부터는 출석부를 돌린 후 10시에 회수하고, 이후에 들어오신 분은 출석 인정을 하지 않겠습니다.

또한 다음 수업부터는 인원수가 체크된 수와 맞지 않으면 다시 체크해서 자리에 없으면 큰 불이익이 있을 예정입니다.

감사합니다.

**Comment by Lee-Nayoung** [comment]
혹시 인원수 체크는 언제하시나요? 바로 다음 수업이 인문대 14동에 있어서 40분 정도에 강의실에서 나가야하는데, 불이익이 있을까요?

**Comment by kim-yoonseung** [comment]
그것은 교수님과 상의해보겠습니다. 아마 그 정도는 감안해주실 것 같습니다.
