### ISSUE TITLE
과제 제출 관련

### ISSUE THREAD

**Issue by freor** [snu-sf-class/pp201602#20]
과제 기한이 오늘까지인 것으로 아는데
어떻게 제출하면 되나요
main.scala 를 조교님 메일로 보내면 되나요?

**Comment by alxest** [comment]
늦어져서 죄송합니다. 제출 사이트 만드는 작업을 마무리 중에 있습니다...

**Comment by HanMH** [comment]
지금도 제출은 불가한 건가요?
바쁘실텐데, 절대 재촉드리는 건 아니고ㅠㅠ
제가 뭐 놓쳤나 걱정되어서 여쭤봅니다.
감사합니다.

**Comment by HanMH** [comment]
지금도 제출은 불가한 건가요?
바쁘실텐데, 절대 재촉드리는 건 아니고ㅠㅠ
제가 뭐 놓쳤나 걱정되어서 여쭤봅니다.
감사합니다.
