### ISSUE TITLE
수업내용과 관련된 질문을 여기에 올려도 되나요? 

### ISSUE THREAD

**Issue by dreamtaker1001** [snu-sf-class/pp201602#22]
조교님하고만 소통하는 공간인가요?

아니면 교수님에게 개인적으로 메일을 보내는것이 나을련지 모르겠네요

프린트 복습하다가 모르는 것이 있어서 어떻게 해야하나 고민되서 질문드립니다.

**Comment by Ailrun** [comment]
https://github.com/snu-sf-class/pp201602#must-read
