### ISSUE TITLE
An issue about WartRemover plugin used by HW1

### ISSUE THREAD

**Issue by Ailrun** [snu-sf-class/pp201602#3]
In HW1, there is linter plugin called as __Wart Remover__ (from here, refer it as __Wart__).
However, by Wart, `List.head` and `List.tail`, and `Option.get`, ... are disabled.

With these restriction, it needs pattern matching to solve HW, at least with my short idea.

Is Wart plugin necessary one? If not, could you get rid of it?

**Comment by alxest** [comment]
Thanks for the report.
As we haven't learned about option type nor pattern match, I will remove this *Wart* rule for now.
I will still keep other rules to prevent students from using "var", "return", etc.

**Comment by alxest** [comment]
I removed it. Please check.

**Comment by alxest** [comment]
If the problem does not go away, then reopen the issue please.

**Comment by Ailrun** [comment]
Actually, I can't reopen this issue because of lack of privilege.
However, the problem is now solved.
