### ISSUE TITLE
과제 제출 서버를 공지합니다.

### ISSUE THREAD

**Issue by alxest** [snu-sf-class/pp201602#30]
README.md 의 submission 섹션을 참고하세요.

**Comment by alxest** [comment]
오늘 중으로 올라오는 문제/질문들에 대해서는 최대한 빨리 처리할 수 있도록 하겠습니다.

**Comment by craig1583** [comment]
제출한 과제가 틀릴 경우 다시 제출할 수 있나요?

**Comment by alxest** [comment]
@craig1583 예, 다시 제출 가능합니다.
과제가 "틀릴 경우"라고 말씀하셨는데요, 관련하여 조금 더 설명드리면
- 기본적으로 과제 제출시에 결과는 SUCCESS/SYSTEM ERROR/COMPILE ERROR(SUBMISSION ERROR) 중 하나로 뜹니다.
  + SUCCESS의 경우에는 테스트를 통과한다는 의미는 아니고, 컴파일되고 테스트 실행에 성공했다는 의미입니다. SUCCESS가 떴어도 실제 점수는 0점일 수도 있습니다. 
  + 실제 점수는 가려져있으며, delay 데드라인까지 끝난 후에는 보이게 됩니다.

**Comment by alxest** [comment]
과제를 여러번 제출했을 때 따로 페널티는 없습니다.

**Comment by alxest** [comment]
문의사항이 있을 때는 *반드시* submission id를 같이 알려주셔야 합니다. 그렇지 않으면 확인할 방법이 없습니다.

**Comment by dohbaek** [comment]
안녕하세요. 과제 1 제출은 문제가 없는데 과제 2 제출시 계속 SYSTEM ERROR가 떠서 문의 드립니다. submission id는 "Submission 474 for Assignment 02"인거 같습니다.

**Comment by alxest** [comment]
@dohbaek 바뀐 스켈레톤에 맞게 고쳐서 제출해주셔야 합니다. https://github.com/snu-sf-class/pp201602/issues/21#issuecomment-252497664

**Comment by dohbaek** [comment]
@alxest 어휴 죄송합니다. 바뀐 스켈레톤에 맞춰서 제출하려고 했는데 프로젝트 두개 띄우고 하다보니 착각을 한거 같아요. 해결되었습니다.

**Comment by alxest** [comment]
서버에서 파일 컴파일은 되는데 type이 skeleton code에서 주어진 것과 달리진 경우에 SYSTEM ERROR라고 뜨던 현상을 수정했습니다. SYSTEM ERROR라고 뜨시는 분들은 다시 제출해보시고 경과를 알려주세요.

**Comment by chanseck** [comment]
과제 1 다시 제출해봐도 SYSTEM ERROR가 사라지지 않습니다.
각각의 ID는 첫번째것이 493, 다시 제출한게 528 입니다.

**Comment by alxest** [comment]
@chanseck object main 의 이름이 object Main 으로 바뀌어있기 때문입니다. 다시 제출하시고 확인해보세요.
