### ISSUE TITLE
[HW2] sbt test에서 import 관련 에러

### ISSUE THREAD

**Issue by minsuu** [snu-sf-class/pp201602#31]
과제를 테스트하는데 있어 `sbt test`커맨드를 사용하고 있습니다.
그런데 이게 HW 1에서는 작동했었는데 HW 2에서는 다음과 같은 import error가 발생했습니다.

```
[error] pp201602-hw-02/src/test/scala/Test.scala:2: not found: object main
[error] import main._
```

에러의 원인을 찾아보려 HW1과 HW2의 `src/test/scala/Test.scala`파일을 비교하고, 약간의 수정을 거쳤더니 `sbt test`가 정상적으로 작동했습니다.

```diff
2c2,3
< import main._
---
> import submission.main._
> import Data._
```

`main.scala`파일이 submission폴더 안에 있으므로 이상해 보이진 않는데요,
본래 `Test.scala`파일이 잘못된 것인지, 혹은 제 sbt 설정에 문제가 있는 것인지 궁금합니다.

**Comment by alxest** [comment]
말씀처럼 수정하는 것이 맞습니다. 수정하여 푸시해두었습니다.
질문 감사합니다.
