### ISSUE TITLE
숙제 제출 서버에 대해서 질문있습니다.

### ISSUE THREAD

**Issue by greemd** [snu-sf-class/pp201602#32]
안녕하세요.

제가 지금 hw02를 제출하니 SYSTEM ERROR가 발생하는데, SYSTEM ERROR가 어떤 경우 발생을 하는지 알 수 있을까요?

**Comment by sangjaekang** [comment]
저 또한 시스템 에러가 납니다. sbt test로는 all pass된 상태입니다. 숙제 1도 success지만 성적이 따로 안나오는데, 혹시 채점이 안된건지 궁금합니다.

**Comment by majecty** [comment]
HW02와 HW03의 경우 최근에 과제의 skeleton code가 조금 수정됐어요.
저도 SYSTEM ERROR가 났었는데 최신 skeleton code와 merge한 뒤로 SUCCESS 떴어요.

#21 
#26

**Comment by greemd** [comment]
말씀하신대로 업데이트된 코드를 받으니 해결되네요!
