### ISSUE TITLE
No main class detected error

### ISSUE THREAD

**Issue by HyjK** [snu-sf-class/pp201602#34]
안녕하세요?
과제 2, 3번을 하던 도중 처음에는 발생하지 않았던(지금도 과제 1번에서는 생기지 않습니다.) 문제가 생겨서 질문을 드립니다.
github에 있는 structure를 그대로 사용했는데도 아래의 에러 메시지가 뜹니다. 
: sb t => compile => run 명령어를 실행했을 때 

`java.lang.RuntimeException: No main class detected.
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) No main class detected.
[error] Total time: 0 s, completed Oct 10, 2016 10:13:20 AM
`

test 는 실행이 가능하고, 과제 제출도 가능하여 일단 제출을 하였는데 문제가 생길지 걱정이 되고,
더불어 해당 이슈를 구글에서 검색해보았는데 제가 잘 이해를 못하여서 질문을 드려요ㅠㅠ 
감사합니다. :)

**Comment by nimooj** [comment]
저도 같은 현상이 발생합니다.
저는 sbt test 시에는 Test.scala 파일의 컴파일이 끝나지 않습니다.

**Comment by alxest** [comment]
@HyjK 
과제02: sbt run 실행시 뜨는 에러는 말 그대로 main class 가 없기 때문에 뜨는 에러이고 정상입니다. sbt test를 실행하시면 테스트가 실행될거에요.
과제03: sbt run 실행시 테스트가 실행될 것입니다. sbt test는 아무것도 실행되지 않을 것입니다.
혹시 위와 다른 행동이 나타나면 다시 말씀해주시길 부탁드립니다. (과제 몇번에서 어떤 명령어 실행을 하신건지)

@nimooj 좀 더 구체적으로 말씀해주시겠어요?

**Comment by alxest** [comment]
컴파일이 안끝나는건 정말로 이상한 행동인데, 한번 취소했다 다시 해보시길 바랍니다. 만약 정말로 안끝난다면 그건 버그에요...

**Comment by nimooj** [comment]
@alxest 
sbt test를 실행했을 때
`[info] Compiling 1 Scala source to /Users/whalegames/Desktop/school/2016-2/pp/hw/pp201602-hw-02/target/scala-2.10/test-classes...` 에서 계속 멈춰져있는데
위에 코멘트 남기고 나서 취소하고 다시 시작했는데 아직까지 계속 같은 상태입니다...
과제 디렉토리는 pp201602-hw-02 오늘 오후 한 시 쯤 클론 받아서 구현한 부분만 다시 넣었습니다..ㅠㅠ

**Comment by alxest** [comment]
@nimooj 혹시 과제 제출하면 어떻게 뜨나요? 제출하시고 submission id 알려주시겠어요?

**Comment by alxest** [comment]
아니면 오피스아워에 직접 오셔도 되고요

**Comment by nimooj** [comment]
@alxest 과제 제출 페이지에서는 SUCCESS가 떠있기는합니다. Submission id는 322이구요. 그래도  sbt test 안되는게 불안하니ㅜㅜ 일단 곧 연구실로 방문드리겠습니다.

**Comment by jeuxdeau** [comment]
@nimooj 어떻게 해결하셨나요? 같은 문제가 생겨서요. sbt compile 하면 컴파일이 잘 끝나는데, sbt test 시에 `[info] Compiling 1 Scala source to...` 에서 멈추어 있습니다.
