### ISSUE TITLE
과제 02 System Error 문의 드립니다.

### ISSUE THREAD

**Issue by sujaelee7940** [snu-sf-class/pp201602#35]
최신 과제 02 파일로 하고 있습니다.

로컬 컴퓨터에서 sbt test는 모두 통과합니다. 

업데이트된 skeleton code로 해서 제출해도 system error가 뜹니다.

submission 폴더 통째로 압축하는거 아닌가요... 어디서 문제가 있는건지 모르겠습니다 ㅜㅜ

**Comment by pigbug419** [comment]
저도 마찬가지입니다 ㅠㅠㅠ
과제 01은 정상적으로 제출이 되는데 과제 02가 system error가 나오네요 ㅠㅠ

**Comment by rhs0266** [comment]
저도 동일한 현상이..

**Comment by wlals31** [comment]
저도 최신 과제로 하고 있는데 동일한 현상이 뜨네요 ㅠㅠ 조교님 답변 부탁드릴게요

**Comment by alxest** [comment]
혹시 submission id를 알 수 있을까요? @sujaelee7940 @pigbug419 @rhs0266 @wlals31

**Comment by wlals31** [comment]
@alxest 2011-10915 입니다

**Comment by alxest** [comment]
음 학번이 아니라 몇번 submission인지가 궁금합니다. 그 숫자를 알 수 있을까요?

**Comment by wlals31** [comment]
@alxest 몇번 submission 이냐는 말씀이 무슨 말씀인 지 잘 모르겠습니다...Assignment 02에 제출하는 과제를 말하는 것이고 submission 폴더는 하나가 아닌가요?

**Comment by alxest** [comment]
제출 사이트에서 SYSTEM ERROR 하이퍼링크 클릭하면, `Submission 36 for Assignment 01` 이런 식으로 submission 숫자가 뜰겁니다. URL을 봐도 알 수 있고요.

**Comment by wlals31** [comment]
289 번입니다 !

**Comment by pocca2048** [comment]
저는 146번입니다

**Comment by sujaelee7940** [comment]
@alxest 283번입니다.

**Comment by pigbug419** [comment]
@alxest 308번 입니다.

**Comment by craig1583** [comment]
310번입니다 동일한 증상입니다.

**Comment by craig1583** [comment]
클래스 정의 부분이 .Data_ 파일에 들어있어서 원래 코드에서 겹치는 부분을 지워주니 해결되었습니다.

**Comment by alxest** [comment]
@craig1583 혹시 조금 더 자세히 설명해주시겠어요?

**Comment by craig1583** [comment]
Main.scala에서 아래 코드(Data.scala에 포함되는 부분)를 지웠습니다.

sealed abstract class IList
case object INil extends IList
case class ICons(hd: Int, tl: IList) extends IList

sealed abstract class Exp
case class EInt(i: Int) extends Exp
case class EAdd(lhs: Exp, rhs: Exp) extends Exp
case class ESub(lhs: Exp, rhs: Exp) extends Exp
case class EMul(lhs: Exp, rhs: Exp) extends Exp

**Comment by alxest** [comment]
아아 네, 그 부분은 이미 공지되었던 부분입니다.

**Comment by alxest** [comment]
@wlals31 문제를 확인해서 수정했습니다. 다시 제출해보시겠어요?
@pocca2048 @sujaelee7940 @pigbug419 님도 확인 부탁드립니다.

**Comment by sujaelee7940** [comment]
@alxest 잘 됩니다. 감사합니다.

**Comment by wlals31** [comment]
@alxest 잘 되네요. 감사합니다 !

**Comment by rhs0266** [comment]
365 번입니다. 아직도 안되는데 전체적으로 해결하는 문제가 아닌가요?

**Comment by pocca2048** [comment]
@alxest  잘 되네요. 확인했습니다!

**Comment by swchoi06** [comment]
@alxest  조교님 제가 지난 10일에 과제를 제출했었는데, 부주의하여 System Error를 SUCCESS로 착각을 하였습니다.

오늘 과제 3번을 확인할 겸 들어가봤더니 System Error라서 깜짝 놀랐습니다. 부랴부랴 확인해보니 코드는 잘못된 것이 없고, Data.scala 파일을 임포트하는 과정에서 문제가 있었습니다.

10일 이전에 제출한 파일이 이미 서버에 올라가 있고, import를 제외하고 다른 부분은 없는데 이 경우에도 딜레이로 인한 감점이 될지 여쭤봅니다ㅠㅠ

submission id는 각각 156, 600 입니다

156은 System Error 가 뜬 버전이고, 600은 SUCCESS 한 버전 입니다.

확인 부탁 드립니다. 감사합니다

**Comment by alxest** [comment]
@swchoi06 음... 안타깝지만 사정을 봐드리기는 어려울 것 같습니다. 숙제 자체의 배점이 크지 않고, 딜레이로 인한 감점도 크지 않으니 위안삼으심이...
