### ISSUE TITLE
error: source file 'submission/Main.scala' could not be found

### ISSUE THREAD

**Issue by kdb4316** [snu-sf-class/pp201602#38]
Status: COMPILE ERROR
Submitted date: Oct. 10, 2016, 2:34 p.m.
Submitted file: submission.zip
Message:
STDOUT:
Compilation Failed!!

STDERR:
error: source file 'submission/Main.scala' could not be found
one error found

----------------------------------
submission 파일 안에, Main.scala 파일이 있고, submission 파일을 zip하여 제출하였으나, 오류가 뜨네요.
제가 뭔가를 잘 못 한건가요??

**Comment by alxest** [comment]
혹시 스켈레톤 코드가 바뀐 부분에 대한 공지를 확인하셨나요? https://github.com/snu-sf-class/pp201602/issues/21#issuecomment-252497664

**Comment by jeuxdeau** [comment]
zip 파일 안에 submission 폴더가 있나요? 저 역시 같은 문제를 겪었는데, zip 폴더 안에 Main.scala 파일만 있고 submission 폴더가 없어서 생긴 에러였습니다. zip 파일 안에 submission 폴더가, 그 안에 Main.scala 파일이 있는지 확인해 보셔요.

**Comment by kdb4316** [comment]
jeuxdeau 님 말씀대로 하니깐 되네요! 감사합니다!!
