### ISSUE TITLE
IntelliJ IDEA 사용시 cbt 버전

### ISSUE THREAD

**Issue by pigbug419** [snu-sf-class/pp201602#4]
![sbt](https://cloud.githubusercontent.com/assets/4942561/18297378/1b6a4632-74eb-11e6-844d-221b8ead6cdd.PNG)

Coursera course's tool setting을 따라서 IntelliJ IDEA 설치 후 사용하고 있는데

IntelliJ 프로그램 내 Scala plugin이 

sbt의 경우 버전이 0.13.8로 명시해 주신 0.13.12버전이 아닌데 이런 경우 문제가 되나요?

**Comment by alxest** [comment]
코세라 툴 세팅은 참고만 하시고, 명시된 0.13.12 버전으로 하시기 바랍니다.
문제가 될 지 안 될지는 잘 모르습니다만, 채점 서버는 0.13.12 버전을 사용할 예정입니다.

**Comment by pigbug419** [comment]
IntelliJ 안에서 sbt version을 0.13.12버전으로 선택할 수가 없는데
그렇다면 아예 IntelliJ를 사용하지 않는것을 권장하시는 것인지요?

**Comment by alxest** [comment]
음... sbt 때문에 IntelliJ를 못쓰는 상황은 없도록 하겠습니다. 
IntelliJ에서 sbt 0.13.12를 사용하기에 어려움이 있다면 채점 서버의 sbt 버전을 낮출 수도 있습니다.
- IntelliJ에서 sbt 0.13.12를 사용할 수 없는 것이 확실한지 확인해보고 싶습니다. 다른 학생들도 같은 문제를 겪는지, 학생들이 구글링해도 방법이 안나오는지 잠시 기다려보겠습니다. 
- IntelliJ에서 사용 가능한 최신 sbt 버전이 어떻게 되나요?

**Comment by Ailrun** [comment]
네 제 경우에도 0.13.8까지만 사용가능한 것으로 나옵니다.
build.properties를 0.13.12로 바꾸어도 이미 세팅된 External Library가 0.13.8로 되어있어서 그 기준으로 돌아가는 것 같네요.

https://github.com/JetBrains/intellij-scala/pulls
에는 0.13.12에 대한 언급이 있는 것으로 보아, 아직 패치가 적용되지 않은 것 아닐까... 합니다만

**Comment by alxest** [comment]
sbt 버전이 문제가 되지 않도록 하였습니다.
https://github.com/snu-sf-class/pp201602/issues/25
