### ISSUE TITLE
과제 1을 제출하고 나면 MySubmission에 표시되는 파일 이름이 바뀌는데 괜찮은 건가요?

### ISSUE THREAD

**Issue by frmh0313** [snu-sf-class/pp201602#40]
과제 제출 서버에 submission.zip을 제출했는데 제출 상태를 확인할 수 있는 부분에서 My Submissions에 나오는 파일이름이 submission_ZAqkfc.zip 이런 식으로 나오는데요. 일단 상태는 SUCCESS로 나오는데 괜찮은 것인가요?

**Comment by Ailrun** [comment]
파일 중복을 막기 위해 이름에 문자열을 덧붙이는 걸로 알고 있습니다.

**Comment by alxest** [comment]
예, @Ailrun 님의 말씀이 맞습니다.

**Comment by frmh0313** [comment]
댓글이 늦었습니다. 조교님, @Ailrun 님 모두 감사드립니다.
