### ISSUE TITLE
과제 제출시 점수 확인

### ISSUE THREAD

**Issue by leegangtoe** [snu-sf-class/pp201602#41]
과제 제출하면 success 라고만 뜨고 점수가 ? 상태입니다. 이게 정상인가요?
1)success는 다 맞은건가요?
2)success가 다맞은 건 아니고 compile만 성공한 것이라면 점수는 별도로 공개하지 않나요?
2-1) 점수가 공개되지 않아도 여러파일을 제출했을때 자동으로 최고점으로 채점되게 되나요?

**Comment by Ailrun** [comment]
1. Success는 정상적으로 컴파일되고 테스트 실행이 가능했다는 의미로 이해해야 할 것 같습니다. 물론 테스트를 통과하여 점수를 받았는지는 별개의 문제겠지요.
2. 점수는 제출 종료일 이후 공개되는 것으로 알고 있습니다.

**Comment by Ailrun** [comment]
https://github.com/snu-sf-class/pp201602/issues/30

**Comment by alxest** [comment]
@Ailrun 님의 답변이 맞습니다.

**Comment by alxest** [comment]
예, 자동적으로 최고점이 채점됩니다.

**Comment by leegangtoe** [comment]
답변 감사합니다. 부가적인 질문인데, 지난학기 허충길 교수님의 programing language 수업을 들을때는 점수를 제출과 동시에 알려줘서 좀더 편했었는데 polycy가 다른 이유라도 있나요?

**Comment by alxest** [comment]
@leegangtoe 이 부분은 교수님께서 결정해주신 것인데, 교수님과 상의해보겠습니다.
