### ISSUE TITLE
테스트시 오류

### ISSUE THREAD

**Issue by SeungyuLee** [snu-sf-class/pp201602#42]
/Users/Kyu/Desktop/ProgrammingPractice/path-to-project/pp201602/hw/02/build.sbt:7: error: not found: value wartremoverErrors
wartremoverErrors ++= (Warts.unsafe.toSet).toSeq
^
[error] Type error in expression

테스트시에 다운받은 build.sbt에서 이런식의 오류가 뜨는데 혹시 해결하신 분 계신가요 ㅠㅠ

**Comment by SeungyuLee** [comment]
일단 wartremoverErrors 부분이랑 wartremoverExcluded 부분 주석처리하니 실행은 되네요!

**Comment by alxest** [comment]
음... 그걸 주석처리하지 않고도 실행이 되어야 합니다.
무슨 명령어를 쳤을 때 저런 에러가 뜬건가요?

**Comment by SeungyuLee** [comment]
sbt test 실행 시에 저런 에러가 뜨네요... 뭐지 ㅠㅠ
스칼라랑 sbt 버전도 확인 다했습니다
not found: value wartremoverErrors와 not found: value wartremoverExcluded만 계속 뜨네요
이 두문장만 주석 처리하면 실행은 되구요.. 이 코드 자체가 뭘 뜻하는건가요?

**Comment by alxest** [comment]
코딩 스타일 강제를 위해 제가 추가한 플러그인입니다.
음 저는 문제가 되는 상황을 재생산하기가 힘들군요... 다른 분들도 같은 문제를 겪으셨나요?
