### ISSUE TITLE
No tests were executed

### ISSUE THREAD

**Issue by wlals31** [snu-sf-class/pp201602#44]
<img width="796" alt="2016-10-11 1 46 40" src="https://cloud.githubusercontent.com/assets/15407536/19259101/5ec81fe2-8fb9-11e6-8c18-72f353592add.png">

다음과 같이 sbt test 명령어를 입력하면
No tests were executed 라는 결과가 나옵니다.

01, 02번 과제와 똑같이 실행을 했는데 왜 이런 결과가 나오는 걸까요...?

**Comment by alxest** [comment]
sbt run을 쳐보시길 바랍니다.
