### ISSUE TITLE
과제 4번 내용 질문드립니다

### ISSUE THREAD

**Issue by lightb0x** [snu-sf-class/pp201602#45]
`def apply: { val a: A ; val e: E } => pair[B, F]`

이 부분이 이해가 안됩니다.

1. 중괄호 마지막 부분이 input인 함수인지, 아니면 input이 type인건지,
2. apply 가 함수인지
3. 함수라면 어떻게 사용할 수 있는지
4. 함수가 아니라면 `assert(mc(strct1, 0, 0, 0, 0, 0, 0, 0, 0).fst == 0)`를 어떻게 성사시킬 수 있는지

모르겠습니다. 도와주세요

**Comment by alxest** [comment]
음... 혹시 수업에서 이런 내용이 안다뤄졌었나요? @kim-yoonseung

**Comment by alxest** [comment]
슬라이드에서
`type gee_type = {val a:Int; def b: Int; def f(z:Int): Int}`
이런 부분이 있는데 혹시 이건 어떤 의미인지 이해하셨나요?

**Comment by lightb0x** [comment]
네 이해합니다.
궁금한 점이 둘 늘었습니다.

1. def apply: { val a: A ; val c: C } => pair[B, D] =
        x => new { val fst = 0 ; val snd = 0}
에서 'x'가 무엇인지
2. commonTy를 작성하는 과정에서 변수의 이름에 따라 ty1의 supertype이 되기도 하고 안 되기도 하는 것으로 보입니다. 만약 그렇다면 ty1의 supertype이면서 ty2의 supertype일 수 없습니다.

**Comment by alxest** [comment]
1. x는 anonymous function의 인자 이름입니다.
2. ??

**Comment by alxest** [comment]
원래 질문
1. 질문의 의미를 잘 모르겠습니다. apply의 타입이 { val a: A ; val e: E } => pair[B, F]라는 뜻입니다.
2. 예, 함수입니다.
3. apply를 바로 불러도 되고 syntactic sugar로 ()로 부를 수도 있습니다. 슬라이드에서 다뤄졌던 내용입니다.
4. 이걸 묻는 숙제기 때문에 답변해드릴 수 없습니다.

**Comment by lightb0x** [comment]
해결했습니다.
다음부터는 더 생각하고 질문 올리겠습니다. 죄송합니다.
