### ISSUE TITLE
과제 제출 문의

### ISSUE THREAD

**Issue by leegangtoe** [snu-sf-class/pp201602#46]
혹시 과제를 제출했을 때 문제별로 test case몇개에 대한 결과를 볼 수 없을까요?
지난번에 과제제출한 것을 확인했는데 실수로 파일을 잘못올려서 함수부분이 ???로 되있는
파일을 올려도 success로 떠서 제대로 제출했다고 착각을 했습니다.
사람마다 개발환경과 채점환경이 조금씩 다를 수도 있고 파일 제출이 제대로 됐는지 
확인이 안되서 좀 불안합니다.
조교님께서 수고스럽겠지만, 혹시 가능하면 실제 점수가 아니라 몇가지 테스트 케이스에 대한 결과를 출력해 주셨으면 합니다.  감사합니다.

**Comment by alxest** [comment]
다음 숙제부터 고려해보겠습니다.
기본으로 드리는 테스트가 제대로 돌아가는지 정도를 체크해드리면 어떨까 합니다.

**Comment by alxest** [comment]
04_new, 05부터는 주어진 기본 테스트가 돌아가는지 테스트하고 있습니다. 한번 확인해보시겠어요?
