### ISSUE TITLE
과제 3번 두 번째 문제 관련 질문입니다.

### ISSUE THREAD

**Issue by frmh0313** [snu-sf-class/pp201602#47]
키값이 같은 것이 들어오면 overwrite하라고 되어있는데, overwrite한 결과는 무엇이 되나요? 
만약 위부터 순서대로 4, 3, 5가 있는 BST에 4가 오면 결과는 그대로 4, 3, 5가 되는 것인가요 아니면 4가 되는 것인가요?

**Comment by alxest** [comment]
4, 3, 5가 키 값을 의미하는거겠죠? 해당 노드만 업데이트되어야 합니다.

**Comment by frmh0313** [comment]
네 키값입니다. 감사합니다.
