### ISSUE TITLE
과제 3번 제출할때 컴파일 에러에 관련해서 입니다.

### ISSUE THREAD

**Issue by eipi100303** [snu-sf-class/pp201602#48]
이렇게 뜨는데 어떻게 해결해야 하나요?

[error] /tmp/tmpvb3wknk0/run/src/main/scala/RunSingleTest.scala:160: not found: value submission
[error]           TryAll { (submission.main.push[String] _).tupled(input) }
[error]                     ^
[error] /tmp/tmpvb3wknk0/run/src/main/scala/RunSingleTest.scala:168: not found: value submission
[error]         val submissionOutput = TryAll { (submission.main.pop[String] _)(input) }
[error]                                          ^
[error] /tmp/tmpvb3wknk0/run/src/main/scala/RunSingleTest.scala:175: not found: value submission
[error]         val submissionOutput = TryAll { (submission.main.deQ[String] _)(input) }
[error]                                          ^
[error] /tmp/tmpvb3wknk0/run/src/main/scala/RunSingleTest.scala:182: not found: value submission
[error]         val submissionOutput = TryAll { (submission.main.insert[Char, Char] _).tupled(input) }
[error]                                          ^
[error] /tmp/tmpvb3wknk0/run/src/main/scala/RunSingleTest.scala:189: not found: value submission
[error]         val submissionOutput = TryAll { (submission.main.lookup[Char, Char] _).tupled(input) }
[error]                                          ^
[error] 5 errors found
[error] (compile:compileIncremental) Compilation failed

**Comment by alxest** [comment]
submission id를 알려주세요.

**Comment by pocca2048** [comment]
`Submission 626` compile error 뜨는데 확인해 주실 수 있으신가요?

**Comment by alxest** [comment]
@pocca2048 에러가 뜨는 것이 맞고 에러가 뜨는 부분을 고치셔야 합니다. 제가 드린 스켈레톤에서 설정을 따로 고치지 않으셨다면, 로컬에서도 에러가 떴었어야 합니다.

**Comment by pocca2048** [comment]
@alxest  그렇군요.. 하지만 깃헙에서 그대로 pull해온 것이지만 제출 마감 전날인 오늘까지 아무런 에러도 뜨지 않았었습니다.

**Comment by alxest** [comment]
@pocca2048 아아 음... 혹시 로컬에서 실행을 어떤 방식으로 하셨었나요?

**Comment by alxest** [comment]
@eipi100303 에러 메세지만 봐서는 디렉토리 압축 구조 자체가 틀린 것 같군요. 압축 풀었을 때 submission 디렉토리 안에 원하는 파일이 있어야 합니다.

**Comment by pocca2048** [comment]
@alxest  `sbt run`으로 test 했습니다

**Comment by alxest** [comment]
음... 그러면 build.sbt를 건드신게 아닌 이상 에러가 떴어야 합니다.

**Comment by alxest** [comment]
@pocca2048 만약 build.sbt를 건드린게 아님에도 그렇다면 지금 상태 그대로 압축해서 저한테 메일로 보내주시거나, github public리포에 올려서 링크를 주시겠어요?

**Comment by alxest** [comment]
@pocca2048 일단 숙제 3번에서는 wart remover를 꺼두겠습니다. 다시 제출해보시면 SUCCESS가 뜰 겁니다.

**Comment by pocca2048** [comment]
@alxest  메일 보냈습니다. 확인 부탁드립니다.

**Comment by eipi100303** [comment]
앗 조교님 제가 과제를 예전에 해서 뼈대 코드가 바뀐줄 몰랐습니다. 그 부분 수정하고 다시 진행하니 제대로 진행되었습니다. 죄송합니다.
