### ISSUE TITLE
emacs에서 ensime 실행 후에도 [ENSIME: Disconnected]

### ISSUE THREAD

**Issue by craig1583** [snu-sf-class/pp201602#5]
![Imgur](http://i.imgur.com/XQXHykh.png)

ensime을 설치하고 hw1파일을 연 후 ensime을 실행했는데 정상적으로 실행은 되나 연결이 되지 않는 문제가 있습니다. 원래는 자동으로 연결되는 것 같은데 해결방안을 알려주시면 감사하겠습니다.

**Comment by Ailrun** [comment]
해당 directory에서 `sbt ensimeConfig` 는 실행하셨나요? 그 이후 다시 ensime을 연결해보시기 바랍니다.

**Comment by craig1583** [comment]
![Imgur](http://i.imgur.com/03zzOnT.png)
sbt에서 ensimeConfig가 실행되지 않습니다..

**Comment by Ailrun** [comment]
http://ensime.github.io/build_tools/sbt/
이곳에서 ensime - sbt plugin을 설치하신 후 진행해보세요

**Comment by craig1583** [comment]
플러그인 설치 후 해결되었습니다 감사합니다
