### ISSUE TITLE
과제 2 컴파일 에러

### ISSUE THREAD

**Issue by timedilation** [snu-sf-class/pp201602#55]
submission number 712입니다
RunSingleTest.scala:94: error: value map is not a member of object submission.main
          TryAll { (Function.tupled (Function.uncurried (submission.main.map _)))(input) }

테스트 돌리면 이상이 없는데 제출하면 위와 같은 에러 메세지들이 뜨네요..

**Comment by alxest** [comment]
본인이 제출하신 파일과 에러 메세지를 보고 생각해보시면 바로 답을 알 수 있을 겁니다.
