### ISSUE TITLE
점수를 바로 보여주실 수는 없나요??

### ISSUE THREAD

**Issue by ctk03272** [snu-sf-class/pp201602#57]
딜레이 기간이 1주일인걸로 알고 있는데요..
숙제 제출 기간만 지나면 바로 점수를 알 수 있고,
혹시나 틀렷을 경우에 딜레이 기간에 수정할 수 있도록
점수를 바로 보여주실수는 없나 여쭙습니다.

**Comment by alxest** [comment]
교수님께 여쭤본 결과, 숙제 채점은 지금처럼 하자고 하셨습니다.
스스로 테스트 케이스 만들어서 테스트 해보는 것도 중요한 능력이니, 제출하기 전에 충분히 테스트 해보고 제출하라고 하셨습니다.
