### ISSUE TITLE
숙제1의 3번 문제에서 몇가지 질문이 있습니다.

### ISSUE THREAD

**Issue by greemd** [snu-sf-class/pp201602#6]
안녕하세요. 
숙제 1의 3번 문제에 대해서 몇가지 질문이 있습니다.

1. 코인값은 전부 다르게 주어지나요?
예를 들어 coins = (2, 2, 2)로 값이 주어지는 경우는 없는건가요?

2. money값이 0인 경우, 경우의 수가 존재하지 않는다고 처리하는게 맞나요?

**Comment by alxest** [comment]
1. 네, 숙제 설명에 추가하겠습니다.
2. 음, money가 0인 경우 아무 동전도 내지 않는 방법 하나가 있다고 생각합시다.
