### ISSUE TITLE
wart 관련 오류

### ISSUE THREAD

**Issue by SeungyuLee** [snu-sf-class/pp201602#60]
<img width="1280" alt="screen shot 2016-10-19 at 11 29 37 am" src="https://cloud.githubusercontent.com/assets/19868687/19503614/c1ed98e0-95ef-11e6-90b2-af7c82572359.png">
<img width="1280" alt="screen shot 2016-10-19 at 11 29 56 am" src="https://cloud.githubusercontent.com/assets/19868687/19503615/c1efb382-95ef-11e6-9855-1a3fa2a92d2d.png">

안녕하세요 조교님. wartRemover 관련해서 문제를 겪고있습니다ㅠㅠ
스칼라 2.11.8 버전 쓰고 있고, sbt는 0.13.12 버전 쓰고 있는데
Resolving org.wartremover#sbt-wartremover;1.1.1 과정에서 계속 문제가 생기네요.. 
	module not found: org.wartremover#sbt-wartremover;1.1.1라고
이 모듈을 찾지를 못하는데 어디서 어떻게 손봐야될 지 전혀 모르겠습니다.

wartremover 깃헙의 이슈를 뒤져봐도 못찾겠고
조교님도 이런 오류 관련해서 다 아시긴 힘들겠지만 혹시 짐작가는 이유라도 있으시면
말씀해주시면 감사하겠습니다.

그전까지는 wart.sbt와 build.sbt에서 wartRemover 관련 코드들을 다 주석처리하고 실행했습니다.
과제 3까지는 문제가 없었는데 과제 4와 이후 과제들에서도 wartRemover 없이 컴파일하면 문제가 있을까요?

**Comment by kim-yoonseung** [comment]
안녕하세요

잠깐 구글링해봤는데, https://github.com/puffnfresh/wartremover 여기에서 sbt 버전을 0.13.5+ 부터 지원한다고 합니다.

혹시 가지고 계신 버전이 이전 예전 버전인가요?

**Comment by SeungyuLee** [comment]
네 혹시나해서 build.properties 에서 sbt 버전을 0.13.5, 0.13.7, 0.13.12 등등으로 해서 실행해봤는데도 마찬가지네요..

**Comment by alxest** [comment]
http://stackoverflow.com/questions/28236192/how-to-fix-this-sbt-resolveexception-unresolved-dependency-commons-loggingco
혹시 .ivy2/cache/org.wartremover 를 rm -rf 하고 다시 돌리면 되나요?

**Comment by SeungyuLee** [comment]
네ㅠㅠ cache 디렉토리를 아예 삭제한다음에 돌려도 그대로네요... 아마 제 랩탑 문제가 아닐까합니다...

**Comment by SeungyuLee** [comment]
sbt 설치에서 문제가 생겼던 것 같습니다. Macports로 설치했던 걸 지우고 Homebrew로 재설치하니까 작동하네요. 번거롭게 해드려 죄송합니다
