### ISSUE TITLE
과제 4번의 함수 사용 관련 질문 드립니다.

### ISSUE THREAD

**Issue by HyjK** [snu-sf-class/pp201602#62]
안녕하세요!
먼저 과제와 관련하여 질문을 드리게 되어 정말 죄송합니다.
혼자서 꽤 오래 고민해보았는데 여전히 모르겠고 시험 전까지도 혼자 이해할 자신이 없어서, 실마리라도 주시면 감사할 것 같아서 질문합니다.
먼저 질문하신 분처럼 myClass에서 apply 함수의 타입 정의 부분이 잘 이해가 가지 않습니다. 

`def apply: { val a: A ; val c: C } => pair[B, D]` 

이 코드에서 apply가 {val a: A; val c: C} => pair[B, D] 라는 타입을 가진 함수라는 것은 알겠습니다.
그런데 제가 apply 함수를 1) 사용함에 있어서 val a, val c 를 어떻게 쓰는지, 2) 정의함에 있어 인자 a, c의 값을 어떻게 주는지 여러 시도를 해보아도 잘 모르겠습니다. 이 부분이 문제의 핵심인 것 같아 사실 질문을 어떻게 드려야 할지 잘 모르겠네요..
1) 예를 들어 currying을 할 때처럼 commonTy 타입 x에 대해 x.apply(a, c) 이런 식으로 a, c의 값을 넣어줄 수 없는 건가요? 리턴값이 { val a: A; val c: C } => pair[B, D] 가 아니라, {val a: A; val c: C} 이 부분을 넣어주어 pair[B, D]만 나오게 하고 싶습니다. 여러 syntax를 시도해보는데 오류가 계속 나서 이게 가능한지부터 여쭤보고 싶었습니다. 

2) a, c 값을 이용해서 위 코드의 => 뒷 부분을 정의하고 싶은데 뒷부분에 a, c를 넣으면 모두 cannot resolve symbol a 가 뜹니다. 즉 pair 가 들고 있는 값들이 a, c에 의해 결정되도록 하고 싶은데 a, c 라는 기호가 인식되지 않네요..
슬라이드에 있는 다른 예시들은 (p.92) 아래처럼 {val a: Int; val b: Int} 라는 값에 대해 s 라는 alias를 주고 있어서 s.b, s.a 같은 식의 접근이 가능한 것 같은데, () 안에 들어 있는 인자가 아니라 {} 에 들어 있는 {val a: A; val c: C} 는 어떻게 접근해야 하는지, 또는 어떻게 값을 넣어야 하는지 잘 모르겠습니다. 
`def foo(s: {val a: Int; val b: Int}) : {val x: Int; val y: Int} = {
object tmp {
val x = s.b
val y = s.a }
tmp }`

아마도 질문하는 내용들이 묻고자 하는 내용과 같거나 비슷할 수 있을 것 같은데,
답변을 직접적으로 줄 수 없다면 혹시 1) 어떤 키워드로 보다 공부를 해보면 좋을지(구글에서 찾아도 비슷한 예시함수를 잘 못 찾겠어서요..) 2) 제가 완전 잘못된 방향에서 고민하고 있는 것이 아닌지 정도와 3) 간단한 피드백이라도 주실 수 있으면 감사하겠습니다.

긴 질문 읽어주셔서 감사합니다. 혼자 공부하다보니 잘 못 따라가는 부분이 많은데, 잘 부탁 드립니다.
좋은 하루 보내세요 :)

**Comment by majecty** [comment]
제가 알고있는 부분이라도 알려드릴게요.

`{val a: A; val c: C}` 의 타입은 record 타입입니다. 
아래 같은 문법으로 record 타입의 값을 만들 수 있습니다.
```scala
val newRecordValue = new { val a = _a; val c = _c}
```
record type의 field를 사용할 때는 (record type 변수).(field 이름) 문법을 사용합니다.
아래 예시 코드처럼 사용하면 되요.
```scala
val person = new { val name = "alice"; val age = 23 }
println(person.name)
```

4번 과제는 function과 record에 대해서 subtyping이 어떻게 정의되는 지를 이해하셔야 풀 수 있어요. 수업시간에 배운 covariance, contravariance, structural typing에 대해서 이해하셔야해요.

혹시 더 궁금하신 게 있으면 알려주세요. 제가 도와드릴 수 있는 부분에서 알려드릴게요.

**Comment by HyjK** [comment]
정말정말 감사합니다!!! 
질문 하나만 더 드리고 싶어요ㅜ! 처음 질문 드린 1)에 관련된 것입니다. 
말씀대로 이 문제에서 ` def apply: { val a: A ; val e: E } => pair[B, F] =
        x => new { val fst = 0 ; val snd = 0}`
이 함수를 사용하고 싶으면 strct2.apply를 쓰면 되는 것 같은데,  여기서 x = {val a: A; val e: E}를 주어야 new 뒤의 값이 도출되는 거 아닌가요...? 
그런데 s = { a, e }  strct2.apply(s)  이런 식으로 사용이 안 되어서 anonymous function에서 인자를 어떻게 넣는지 이해가 잘 되지 않습니다.ㅜㅜ

**Comment by majecty** [comment]
strct2에 레코드 타입의 인자를 넣어서 호출하고 싶으시다면 다음과 같이 하시면 됩니다.
A타입의 _a값과, E타입의 _e 값이 있을 때 다음처럼 호출하면 되요.
```
strct2.apply(new { val a= _a; val e = _e })
```

**Comment by HyjK** [comment]
감사합니다!!! 새로운 record type을 형성해서 apply에 넘겨주는 개념인가봐요(제가 이해한 바로는)! 
왜인지는 잘 모르겠지만 처음에는 Object{type ~~~; type~~~ }여서 {type ~~~; type~~~} 와 달라서 type mismatch라고 뜨더니 조금 기다렸더니 되네요!

감사합니다. :):)
