### ISSUE TITLE
과제 5번 eq 이름 변경 건의

### ISSUE THREAD

**Issue by majecty** [snu-sf-class/pp201602#63]
안녕하세요. 과제 5번의 skeleton code에 대해서 제안드릴 게 있어요.

과제 5번에서 값 2개를 비교하는 함수의 이름으로 `eq`라는 이름을 사용합니다.
하지만 eq는 scala에서 이미 사용하고 있는 이름입니다. scala repl 에서 `"a" eq "a"`를 쳐서 확인해보실 수 있어요.

문제는 과제를 하는 도중 eq를 잘못 사용할 시 과제 코드에서 정의된 eq가 아니라 scala에 원래 정의되어 있던 eq가 불려서 이상한 에러메시지가 뜨게 됩니다. 특히 `eq("a","b")` 식으로 튜플 값을 넣는 실수를 하는 경우 결과값이 항상 false가 나오게 됩니다. (함수를 잘못된 문법으로 불렀는데 컴파일 에러가 나지 않습니다!)

저도 친구가 먼저 고생하고 미리 알려주어서 쉽게 해결했지만, 이런 부분을 처음 만난 다른 분들은 많이 혼란에 빠지실 수 있을 거 같아요.

과제에서 eq라는 이름 대신 다른 이름을 사용하면 좋겠습니다.

**Comment by Ailrun** [comment]
eq(1,1) 같은 경우

eq가 AnyRef.type의 member 로 인식되어 (왜 그렇게 인식하는지는 모르겠습니다만)

type vs Tuple 비교를 하게되는데, 이 경우 당연히 false가 나오게 됩니다. 이외에도 eq에 서로 다른 타입의 값 두 개를 넣어보시면 false가 나오는 걸 확인하실 수 있으실 겁니다.

타입에러가 나오지 않는건, eq가 AnyRef -> Boolean 인 참 약한 타입의 function 이기 때문입니다.

**Comment by Ailrun** [comment]
하나 더 참고로, eq는 AnyRef 를 상속받는 임의의 사용자 정의 타입들 (객체, 레코드 등)의 멤버로 속해있는 메소드입니다.

**Comment by alxest** [comment]
좋은 건의 감사합니다. 바꿔보겠습니다.

**Comment by alxest** [comment]
저는 저런것들 (object의 기본 method 들)이 스칼라 언어에 왜 드러나야하는지 정말 모르겠어요... 스칼라 gitter에도 물어봤었는데 java 쓰는 사람들 쉽게 끌어오는거 말고는 use case를 전혀 모르겠습니다, 언어는 더러워지고...

**Comment by alxest** [comment]
eqFunc로 이름을 고쳤습니다. equals 같은 이름도 이미 선점되어있어서..
