### ISSUE TITLE
24일 월요일 수업이 았는지 궁금합니다.

### ISSUE THREAD

**Issue by rhs0266** [snu-sf-class/pp201602#65]
24일 월요일 수업이 았는지 궁금합니다.

**Comment by HyjK** [comment]
교수님께서 다음주 양일 모두 휴강이라고 말씀하셨습니다.

단 덧붙여 질문을 드리자면 수업 끝나고 교수님께 문의를 드렸을 때 '연구실에 와서 질문을 하는 것이 가능하게 하거나 아니면 질문을 받는 수업을 열어주시는' 쪽으로 생각을 해보겠다고 하셨었는데 이 부분에 있어서 혹시 조교님과 논의가 있었는지 궁금합니다.
그리고 혹시 가능하다면 실습실에서 질의응답 세션을 열어주시면 좋을 것 같습니다! 시험 전에 실습실 스칼라 세팅에도 익숙해지고 시험이 어떤 식으로 치러질 지 조금더 감을 잡기 좋을 것 같아서요!

**Comment by alxest** [comment]
휴강이라고 하셨습니다. 관련하여 방금 공지하였습니다. https://github.com/snu-sf-class/pp201602/issues/66

**Comment by alxest** [comment]
@HyjK 
`연구실에 와서 질문을 하는 것이 가능하게 하거나 아니면 질문을 받는 수업을 열어주시는` 
- 음, 질문을 언제 하신건가요? 몇주 전에 하신거면, 예 논의가 있었고 관련하여 README.md에 공지해두었습니다.
```
Office Hour:
    Professor: 407 Bldg 301, 13:00-14:00 Mon
    TA: 416 Bldg 301, 14:00-15:00 Mon
```
- `실습실에서 질의응답 세션을 열어주시면 좋을 것 같습니다!` 음 정확히 어떤 부분이 궁금하신건가요? 실습실에 스칼라가 이미 세팅되어있으니, 가서 사용해보시고 문제가 있으면 문의해주셔도 될 듯 합니다. 시험 환경 부분은 다른 조교님께서 담당해주기로 하셨으니, @kim-yoonseung 조교님께 여쭤봐주시길 부탁드립니다.

**Comment by HyjK** [comment]
질문/답변 지난 수요일(10월 19일)의 일입니다! 
IDE 사용할 수 있나요...? 아니면 터미널에서? 사실 이번 학기 실습실을 한 번도 가보지 않아서 드리는 질문이지만 답변해주시면 감사하겠습니다.

**Comment by alxest** [comment]
@HyjK 
- `오피스 아워에 방문을 못하는 사람들도 있을 테니 휴강인 대신 수업 시간 중에 질의을 받아주실 수 있냐 정도의 의도로 드린 질문이었어요.`
관련하여 교수님께서 저와 논의하시지는 않으셨습니다. 저는 그 시간에 제가 듣는 수업이 있어서 질의를 받지 못합니다.
만약 논의가 있었다면 수업 조교분과 논의가 있었을 듯 합니다. @kim-yoonseung 
- 위에서 말씀드린 것처럼, 시험 환경 관련해서는 저는 잘 모릅니다. 일전에 제가 바쿠스에 부탁해서 IntelliJ가 설치되었다고 들었습니다만, 사용해본 적은 없습니다.

**Comment by kim-yoonseung** [comment]
안녕하세요
우선 저는 따로 수업시간에 질의를 받는 세션을 여는 것에 대한 얘기를 듣지는 못했습니다.
그래서 강의실이나 실습실을 예약하지는 못했습니다.
하지만 월/수 양일 수업 시간에 자유롭게 저희 연구실(301동 416호)로 오셔서 질문하시면 제가 답변을 해드리겠습니다. 이렇게 하는 게 학생분들도 시간을 유연하게 쓸 수 있으니 좋을 것 같습니다.
물론 시험 문제에 대해서는 저도 알지 못하지만 과제나 수업 내용에 대해서는 답변해드릴 수 있습니다.

시험실 환경은 리눅스에 intellij IDEA를 설치해 놓은 것으로 들었는데, 다음 주 주중에 제가 확인할 예정입니다.
실습실 환경에 익숙해지기 위해 실습실에서 저희가 질의응답을 하는 것은 사실 효과가 있을지 모르겠습니다. 제가 한 번 테스트해보고 간단한 가이드가 필요하다고 느끼면 이 게시판 등으로 알려드릴테니 각자 비는 시간에 실습실에서 체크해보는 게 어떨까요?

**Comment by HyjK** [comment]
네 그 정도면 충분할 것 같아요! 
실습실에 가본 적이 없어서 IntelliJ가 깔려있는지도 몰랐기 때문에 여쭤본거라, 다른 게 크게 필요할 것 같지는 않습니다. 
감사합니다. :)
