### ISSUE TITLE
[공지] 노트북 빌려가신 학생들께

### ISSUE THREAD

**Issue by kim-yoonseung** [snu-sf-class/pp201602#7]
안녕하세요 수업조교입니다.

강의 중 나눠드린 노트북이 2대가 나갔는데, 어느 분이 가져가셨는지 저희가 알아두어야 할 것 같습니다.

가져가신 분은 조교 메일(pp201602@sf.snu.ac.kr)이나 댓글로 이름 / 학번을 알려주셨으면 합니다.

감사합니다.

**Comment by ctk03272** [comment]
전태경 / 2008-10961입니다.
