### ISSUE TITLE
숙제 04 관련

### ISSUE THREAD

**Issue by alxest** [snu-sf-class/pp201602#70]
제 실수로 숙제 04의 답안이 유출되어서 지금의 숙제 04를 무효화합니다.
숙제 04는 약간 변형된 채로 다시 출제될 예정이며, 데드라인은 지금의 딜레이 데드라인인 10월 31일입니다. 곧 다시 공지하겠습니다.
불편을 끼쳐드려 죄송합니다.

**Comment by lightb0x** [comment]
유출이 언제 되었나요?

유출 되기 전에 제출했어도 새로 제출해야 하나요?
시험기간이라 데드라인에 맞추기 힘들것같은데요.

**Comment by alxest** [comment]
@lightb0x 10월 17일 새벽 2시 10분에 되었습니다.
원래 숙제를 자력으로 해결하신 분이면 10분 이내에 해결 가능하도록 수정할 예정입니다.
