### ISSUE TITLE
과제3 채점관련 질문

### ISSUE THREAD

**Issue by sejoonoh** [snu-sf-class/pp201602#75]
안녕하세요, 

과제 3에 problem 3의 2번째 case가 다음과 같이 틀렸다고 나오는데요.

[[FAIL]]
Input: (MyCons(㴨솎牼哷撚괃ᛤꠧ௑륈䤐欃ਥ绅뱡펃䥜섅뒈䴨,MyNil),MyCons(慞苵ᒜ颵⒚떌괋៲朏홙뗿Ǩ㽗䑠뺜Ξ饛隔썤앫,MyNil))
Submission Output: Some((慞苵ᒜ颵⒚떌괋៲朏홙뗿Ǩ㽗䑠뺜Ξ饛隔썤앫,(MyNil,MyCons(㴨솎牼哷撚괃ᛤꠧ௑륈䤐欃ਥ绅뱡펃䥜섅뒈䴨,MyNil))))
Solution Output: Some((㴨솎牼哷撚괃ᛤꠧ௑륈䤐欃ਥ绅뱡펃䥜섅뒈䴨,(MyNil,MyCons(慞苵ᒜ颵⒚떌괋៲朏홙뗿Ǩ㽗䑠뺜Ξ饛隔썤앫,MyNil))))

제가 해석한 바로는 Input이 Queue = (stk1 = "A", stk2 = "B") 꼴이고
이것을 deQ하는게 문제인거 같은데,
solution의 경우, stk1의 원소 A를 pop해서 stk2에 push한 다음, pop(stk2)로 A를 출력한다고 생각되고,
제 답안은, B를 출력하고 A를 stk2에 옮깁니다.

저는 stk2의 원소가 항상 stk1의 원소보다 먼저 queue에 push 되었다고 가정해서 deQ했을때 B를 먼저 출력했는데, 이 가정이 틀린건가요?

감사합니다.

**Comment by HyjK** [comment]
안녕하세요! 저도 질문 주신 분과 비슷한 아이디어로 조금 다른 구현을 하였서 댓글에 남깁니다. 
동일한 과제 3 문제 3 2번째 케이스에서 저도 B에 원소가 있을 경우 A에 있는 원소보다 먼저 enQ된 것이라고 가정하였습니다.
구현이 다른 부분은 과제 설명에 '   Or you may further optimize this by merging only when needed.' 라는 구절이 있어 B에 원소가 있을 경우에는 merge를 아예 하지 않았습니다. 즉 deQ(~~~)를 했을 때 B의 원소가 비어 출력할 것이 없는 경우에만 merge를 진행하여, 해당 케이스의 경우에는 A에서 B로 원소를 옮기지 않습니다. 

그래서 deQ의 결과값으로 출력이 되는 원소는 질문해주신 분과 동일한 원소가 출력되고, Queue = (stk1, stk2)는 다른 형태로 출력이 됩니다. 

[[FAIL]]
Input: (MyCons(㴨솎牼哷撚괃ᛤꠧ௑륈䤐欃ਥ绅뱡펃䥜섅뒈䴨,MyNil),MyCons(慞苵ᒜ颵⒚떌괋៲朏홙뗿Ǩ㽗䑠뺜Ξ饛隔썤앫,MyNil))
Submission Output: Some((慞苵ᒜ颵⒚떌괋៲朏홙뗿Ǩ㽗䑠뺜Ξ饛隔썤앫,(MyCons(㴨솎牼哷撚괃ᛤꠧ௑륈䤐欃ਥ绅뱡펃䥜섅뒈䴨,MyNil),MyNil)))
Solution Output: Some((㴨솎牼哷撚괃ᛤꠧ௑륈䤐欃ਥ绅뱡펃䥜섅뒈䴨,(MyNil,MyCons(慞苵ᒜ颵⒚떌괋៲朏홙뗿Ǩ㽗䑠뺜Ξ饛隔썤앫,MyNil))))

가정 및 상이한 구현 방식에 대한 답변 주시면 감사하겠습니다...! 고생 많으세요..

**Comment by sejoonoh** [comment]
@HyjK 저도 처음에 A에서 B로 원소 옮기지 않고 제출했는데, 틀린거 발견하고 merge하는 식으로 고쳐서 냈다가 또 틀리길래 input을 자세히 살펴보다가 다른 점을 발견해서 글을 올리게 되었습니다.

**Comment by alxest** [comment]
예, 제 실수입니다. 채점 스크립트를 수정하고 재채점한 후 공지하겠습니다.
혹시 재채점 후에도 문제가 생기면 다시 말씀해주세요.

**Comment by alxest** [comment]
그리고 submission id를 알려주셔야 재채점이 제대로 되었는지 제가 확인해볼 수 있습니다.

**Comment by jeuxdeau** [comment]
저는 merge 방식을 한 스택에서 다른 스택으로 옮기는 것으로 설명해 주셨길래 뒤에 오는 스택은 비어있을 것이라 가정했는데요... only when needed는 웬만하면 수정하지 말라는 뜻으로 받아들여졌고요.

**Comment by alxest** [comment]
구현에 상관없도록 채점 스크립트를 수정할 예정입니다.

**Comment by alxest** [comment]
그리고 submission id를 알려주셔야 재채점이 제대로 되었는지 제가 확인해볼 수 있습니다.
