### ISSUE TITLE
실습실 intellij IDE

### ISSUE THREAD

**Issue by leegangtoe** [snu-sf-class/pp201602#78]
현재 실습실에 intellij IDE에서 scala를 사용할 수없는 것 같은데 언제쯤 사용이 가능해 질까요?
intellij에서 작업해 본적이 없어서 시험전에 한번쯤 써보고 싶습니다.

**Comment by kim-yoonseung** [comment]
제가 설치가 되어있는 것은 확인했는데, 혹시 터미널에서 idea.sh를 입력하면 실행이 되지 않나요?

**Comment by kim-yoonseung** [comment]
실습실에서 intellij로 scala를 사용해봤는데 간단히 테스트해보니 동작합니다.
처음 intellij를 켜면 세팅이 조금 오래 걸리곤 하는데, 시험 시간이 여유가 많으므로 큰 영향은 없을 듯합니다.

**Comment by leegangtoe** [comment]
제가 켰을때는 project JDK와 scala SDK가 없다고 나오는데 어떻게 해야 하나요??

**Comment by kim-yoonseung** [comment]
제가 본 것과 같은 메시지인지 모르겠지만, 저의 경우에는 New를 눌러서 나오는 디렉토리 중 openjdk인가 하는 것으로 시작하는 디렉토리를 선택했더니 되었습니다.

**Comment by leegangtoe** [comment]
그렇게 하면 되내요. 감사합니다!
