### ISSUE TITLE
run button 이 활성화가 되지 않습니다

### ISSUE THREAD

**Issue by dreamtaker1001** [snu-sf-class/pp201602#8]
![image](https://cloud.githubusercontent.com/assets/22032014/18407213/41e4c8bc-7745-11e6-94fc-8d687b9e2296.png)

탭에 보면 빨간색(핑크색)으로 두줄이 가있고

튜토리얼에 있는 것처럼 run button이 활성화 되지 않습니다. 

혹시 어떤 문제가 있을려나요?

windows 10 intellj 2016.2 community입니다.

**Comment by alxest** [comment]
음... 저는 windows/intellij를 안써봐서 잘 모르겠습니다. 그리고 튜토리얼을 안 보더라도 과제하는 것에는 지장이 없으리라 생각합니다.
run button 이 아마도 command line 에서 sbt run 치는 것에 해당될 것 같은데, 직접 쳐보면 에러 메세지가 나올 것 같기도 합니다. run 이전에 sbt compile 하면 잘 되나요?

**Comment by dreamtaker1001** [comment]
@alxest 튜토리얼을 다시보니 scala class를 선택한후 kind에서 제가 object로 바꿔야하는데 그대로 class로 가서 그랬던것이었네요 답변 감사합니다.

**Comment by alxest** [comment]
해결되었다니 다행이군요.
이슈는 닫겠습니다.
