### ISSUE TITLE
시험 방식에 관한 몇 가지 질문

### ISSUE THREAD

**Issue by minsuu** [snu-sf-class/pp201602#81]
1. 실습실에서 로그인은 자신의 아이디를 사용하나요? 아니면 임시로 생성된 아이디를 사용하나요?

2. 문제를 푸는 방식이 과제와 같이 skeleton이 주어지는 방식인가요? 아니면 새로운 sbt poject를 만들어야 하나요?

3. 시험 중에 score는 오픈되지 않는 방식인가요? 교수님께서는 시험을 나갈 때 점수를 알 수 있을거라고 말씀하셨던 것 같은데, 과제와 다른 방식이라서요..

**Comment by alxest** [comment]
2. 숙제와 비슷할 것입니다.
3. 역시 숙제와 비슷하게 오픈되지 않습니다. 시험 끝난 직후에는 바로 오픈 가능할 듯 해요. (딜레이가 없으니)
