### ISSUE TITLE
과제 6 질문입니다.

### ISSUE THREAD

**Issue by rhs0266** [snu-sf-class/pp201602#82]
과제 6 질문입니다.

biIter에서 Next를 본래 크기보다 훨씬 많은 회수를 호출한 다음에 Prev를 호출하면 List의 마지막 원소가 나오나요, 아니면 None이 나오나요??

**Comment by alxest** [comment]
List의 마지막 원소가 나옵니다.

**Comment by HyjK** [comment]
테스트에 assert(bx.biIter.getNext.getNext.getNext.getValue == None)라고 되어 있어서 None이 맞다고 이해했는데 아닌가요?

**Comment by alxest** [comment]
그건 None이지만 거기서 getPrev 하면 다시 마지막 원소가 나와야 합니다.

**Comment by rhs0266** [comment]
감사합니다!

**Comment by HyjK** [comment]
감사합니다!
