### ISSUE TITLE
과제 06 btree 질문

### ISSUE THREAD

**Issue by leegangtoe** [snu-sf-class/pp201602#83]
tree node의 연결관계가

Node("A", Node("B", Empty(), Node("D",Empty(),Empty())), Node("C", Empty(), Empty()))
일때 A부터 순서대로 get_next를 해서 내려오면  
A B C none D none none none none none
이 순서가 맞는 건가요?

**Comment by Ailrun** [comment]
ABDC none 아닌가요??
inorder traverse 로 해서...

**Comment by alxest** [comment]
윗 댓글이 맞습니다. 수업에서 배운 순서대로입니다. (inorder traverse)

**Comment by alxest** [comment]
죄송합니다, 제가 정신이 없어서 단어를 잘못 적었었네요.
윗 댓글이 맞고, 수업에서 배운 대로이고, *preorder traverse* 입니다.
이산수학 시간이 아니니 간단히 말씀드리면
inorder: left value right
preorder: value left right
postorder: left right value
라고 생각하시면 됩니다.
