### ISSUE TITLE
과제 04_new func 관련 질문

### ISSUE THREAD

**Issue by Rajin9601** [snu-sf-class/pp201602#87]
ty1, ty2의 apply 함수 안에서 func를 받기 때문에
맨 밑에 있는 apply 함수에서 func를 받아야 하지 않나요?

**Comment by minsuu** [comment]
저도 이 부분이 명확하지 않다고 생각이 들어요. func가 맨 아래 apply의 parameter가 아니니까, type에 맞게 각각 1:1매핑을 하는 항상 같은 값을 리턴하는 함수를 맨 아래 apply 정의 내에서 구현하라는 것이 의도인 것 같아요.

**Comment by alxest** [comment]
@minsuu 님의 말씀처럼 구현하시면 됩니다.
