### ISSUE TITLE
시험 문제 3번

### ISSUE THREAD

**Issue by leegangtoe** [snu-sf-class/pp201602#89]
이번 시험에서 문제 3번을 풀면서 Spec에 type이 Any를 포함해서는 안된다는 말이 없어서
코드에 Any를 포함한 상태로 풀어서 제출을 했고, 제출한지 1시간이 넘은 후, 종료 5분전에야 컴파일 결과를 확인할 수 있었는데 컴파일 에러가 떴습니다. 

문제 상에서 정확히 쓰면 안된다고 주어지지 않았고, 별도의 공지도 없어서 로컬에서 컴파일 되는 것을 확인하고 제출을 하였고, 그 결과도 서버가 느려서 종료 직전에야 확인할 수 있었는데 좀 억울한 면이 없잖아 있다고 생각합니다.

혹시 이 문제에 관해 구제 방안이 있는지 궁금합니다.

**Comment by rhs0266** [comment]
헐.. 펜딩이 한시간 넘게 남은것같아서 나왔는데 Any 안되나요...ㅜ

**Comment by SeungyuLee** [comment]
전 컴퓨터 문제로 로컬에서도 컴파일을 못했고 서버도 너무 느려서 컴파일 결과를 확인하지 못하고 나왔는데ㅠㅠ 컴파일 에러인 경우에는 그냥 0점인가요?

**Comment by alxest** [comment]
- @leegangtoe @rhs0266 @SeungyuLee 확인을 위해 학번을 알려주시겠어요? 이런 문제로 억울한 점이 없도록 노력해보겠습니다.
- 로컬에서 컴파일 되던게 서버에서 안되는거는, (과제에도 계속 있었던) sbt plugin 때문입니다.
서버에서 채점할 때 var/exception/runtime type casting 등을 막기 위해서 이 plugin을 쓰는데, 이 plugin의 기본 설정 중에 Any로 infer 되는 것을 막는게 있습니다. (explicit 하게 쓴 것은 허용)
시험 볼 때는 학생분들이 sbt로 실행을 못했었고, 서버가 제때 제때 컴파일 결과를 보여주지 못했으니, 이 plugin 때문에 로컬에서 컴파일 되던게 서버에서는 안되는 경우는 없도록 노력해보겠습니다. 다만 var/runtime type casting 등은 애초에 배우지를 않았고 쓰면 안되는거니까, 이런 것만 막도록 plugin 설정을 바꿔서 채점을 돌리면 될 것 같습니다.
- 정확히 어떻게 할 지는 교수님께 여쭤보고 공지하겠습니다.

**Comment by alxest** [comment]
타입을 { } 대신 Any를 쓰신거죠?

**Comment by rhs0266** [comment]
2014-16371 입니다

**Comment by leegangtoe** [comment]
2013-12096 입니다. 주말에 답변 감사합니다.

**Comment by leegangtoe** [comment]
2013-12096 이강토입니다.
주말에도 답변해 주셔서 감사합니다.

**Comment by SeungyuLee** [comment]
2013-13388입니다!

**Comment by young146777** [comment]
저는 3번 문제를 Any를 포함하게 해서 만들고 올렸다가(로컬에서는 잘 돌아갔습니다.) 숙제에서 Any를 쓰면 컴파일 에러가 난다는 사실을 알고 있어서 나중엔 양쪽의 supertype을 찾는 것을 포기하고 하나만 만족하도록 제출했는데, 이런 경우는 어떻게 하나요?

**Comment by alxest** [comment]
@young146777 파일 올리셨던게 있는건가요? 일단 학번을 알려주시겠어요?

**Comment by young146777** [comment]
2011-12442입니다 !

**Comment by alxest** [comment]
@leegangtoe @rhs0266 @SeungyuLee 윗 댓글에 적었던 것처럼, 해당 플러그인의 설정을 변경한 후 채점하기로 하였습니다. https://github.com/snu-sf-class/pp201602/issues/90

**Comment by alxest** [comment]
@young146777 학생의 경우에도, 말씀하신 Any를 쓴 답안을 인정해드리겠습니다.
