### ISSUE TITLE
과제 5번 내용문의

### ISSUE THREAD

**Issue by frmh0313** [snu-sf-class/pp201602#94]
혹시 IterDictImpl에서 add 구현시 새로 추가된 것이 뒤에 추가되어도 괜찮은 것인지 궁금합니다. 
그리고 overwrite할 때도 키가 같은 것이 발견된 자리에 바로 overwrite해도 과제 채점시에는 문제가 없나요? 
시험 볼 때는 조건에 대해서 조교님이 이야기하셨던 것 같은데, 과제 주석에는 이 부분에 대한 특별한 언급이 없는 것 같아서 어떤 기준으로 채점되는지 궁금합니다.

**Comment by alxest** [comment]
네, 괜찮습니다. 숙제 채점에서는 IterDictImpl을 Map으로 변환해서 같은지 여부를 체크하고 있습니다.

**Comment by alxest** [comment]
비슷하게 getNext/getPrev의 행동도 시험과 숙제에서 미묘하게 다릅니다만, 이런 부분까지 채점하지는 않을 듯 합니다.

**Comment by frmh0313** [comment]
네. 감사합니다.
