### ISSUE TITLE
과제 제출할때에는 success라고 떴었는데 이후 결과가 컴파일에러로 바뀐것은 무엇인가요?

### ISSUE THREAD

**Issue by chickenbear** [snu-sf-class/pp201602#97]
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 10 s, completed Nov 2, 2016 2:44:56 PM
라는 것은 오늘 2시 44분에 컴파일한 결과 컴파일에러가 떴다는 뜻인가요?

**Comment by alxest** [comment]
오늘 채점 스크립트를 바꾸고 재채점을 돌렸습니다.

**Comment by alxest** [comment]
어제 더 생각을 해보았는데요, 사정을 봐드리기 어려울 것 같습니다. 로컬에서 테스트를 돌리는 방법을 모르셨다면 미리 물어보셨어야 합니다.
