### ISSUE TITLE
04_new 재채점 딜레이 여부

### ISSUE THREAD

**Issue by timedilation** [snu-sf-class/pp201602#98]
원래 테스트케이스에서는 success였는데 수정된 테스트케이스에서는 compile error가 떴습니다.
지금 이미 기한이 지났는데 수정해서 내면 딜레이로 처리되나요?

**Comment by pigbug419** [comment]
@alxest 
저도 원래 success였는데 채점스크립트를 바꾸고 재채점을 하신 후에는 compile error가 떴습니다.
제가 숙제를 제대로 제출하지 못한 건가요 아니면 아직 재채점을 하기 전인가요

**Comment by alxest** [comment]
네, 이 경우 로컬에서 테스트를 돌려보았다면 미리 알 수 있었던 문제라서 사정을 봐드리기 어려울 듯 합니다.

**Comment by timedilation** [comment]
넵.. 프로젝트에 포함되어있던 테스트케이스는 통과했는데, 새로 더 테스트케이스를 만들었으면 확인가능했다는 의미이신거죠..?

**Comment by alxest** [comment]
음.. submission id를 알려주시겠어요?

**Comment by timedilation** [comment]
1046번입니다!

**Comment by alxest** [comment]
음 일단 제대로 된 솔루션을 다시 제출하시고요, delay 처리를 어떻게 할 지는 나중에 다시 생각해보겠습니다.

**Comment by pigbug419** [comment]
저도요...ㅠㅠ 1101번입니다!!

**Comment by Choi-Jaehyeok** [comment]
1011번도 다시 제출해도 될까요ㅠㅠ

**Comment by ctk03272** [comment]
음.. 저같은 경우에도 썩세스 였던것이 컴파일 에러가 뜨는데요...
다시 제출해도 될런지요...

**Comment by alxest** [comment]
아직 방침이 정해지지는 않았습니다만, 일단 서버에 기록이 남아야하니 다시 제출해둬보시기 바랍니다.
