### ISSUE TITLE
숙제 6번을 풀다가 질문이 있습니다

### ISSUE THREAD

**Issue by sangjaekang** [snu-sf-class/pp201602#99]
임의의 타입 A에 대해서 특정한 값을 가진 상수를 어떻게 정의할 수 있을까요?
 class ListIter[A](val list: List[A]) extends BiIter[A] { ....}

에서 list[A]라는 인자가 있습니다.   이 list의 마지막 element 뒤에

특정한 element를 추가시켜, 리스트의 끝임을 표시하고 싶은데, 

모든 타입에 대해서 호출가능한 특정 값을 가진 상수를 정의가능하나요?

**Comment by alxest** [comment]
그런게 불가능한게 좋은 성질인데, 일단 스칼라는 가능합니다. 어떻게 가능한지는 알려드리지 않겠습니다, 안좋은 프로그래밍 방식입니다.
이슈에서 묘사된 것만 보면, 수업 시간에 배운 패턴매치로 해결 가능한 듯 합니다.
